# Generated by Django 5.2.17 on 2026-08-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.CreateModel(
            name='NhaMay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ma_nha_may', models.CharField(max_length=50, unique=True)),
                ('ten_nha_may', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nhà máy',
                'verbose_name_plural': 'Nhà máy',
                'db_table': 'khovattu_bang_nha_may',
            },
            )],
        ),
    ]
