# Generated by Django 5.1 on 2026-05-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SonghinhMnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mucnuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dungtich', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sông Hinh Mnh',
                'verbose_name_plural': 'Sông Hinh Mnh',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThuongKonTumMnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mucnuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dungtich', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thượng Kon Tum Mnh',
                'verbose_name_plural': 'Thượng Kon Tum Mnh',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vinhson_HoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mucnuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dungtich', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vĩnh Sơn - Hồ A',
                'verbose_name_plural': 'Vĩnh Sơn - Hồ A',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vinhson_HoB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mucnuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dungtich', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vĩnh Sơn - Hồ B',
                'verbose_name_plural': 'Vĩnh Sơn - Hồ B',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vinhson_Hoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mucnuoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dungtich', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vĩnh Sơn - Hồ C',
                'verbose_name_plural': 'Vĩnh Sơn - Hồ C',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
