# Generated by Django 3.2.25 on 2026-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongsoSanxuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nha_may', models.CharField(default='songhinh', max_length=50)),
                ('thoi_gian', models.DateTimeField()),
                ('cot_c', models.FloatField(blank=True, null=True, verbose_name='Hồ chứa')),
                ('cot_d', models.FloatField(blank=True, null=True, verbose_name='Mực nước kế hoạch')),
                ('cot_f', models.FloatField(blank=True, null=True, verbose_name='Mực nước chết (m)')),
                ('cot_g', models.FloatField(blank=True, null=True, verbose_name='Mực nước thượng lưu (m)')),
                ('cot_h', models.FloatField(blank=True, null=True, verbose_name='Dung tích hữu ích (tr.m3)')),
                ('cot_i', models.FloatField(blank=True, null=True, verbose_name='Lưu lượng nước về Qv (m3/s)')),
                ('cot_j', models.FloatField(blank=True, null=True, verbose_name='Lưu lượng qua máy Qcm (m3/s)')),
                ('cot_k', models.FloatField(blank=True, null=True, verbose_name='Lưu lượng xả lũ Qxl (m3/s)')),
                ('cot_l', models.FloatField(blank=True, null=True, verbose_name='Sản lượng Qc ngày')),
                ('cot_m', models.FloatField(blank=True, null=True, verbose_name='Đầu cực ngày')),
                ('cot_n', models.FloatField(blank=True, null=True, verbose_name='Thương phẩm ngày')),
                ('cot_o', models.FloatField(blank=True, null=True, verbose_name='Sản lượng Qc Ao giao tháng')),
                ('cot_p', models.FloatField(blank=True, null=True, verbose_name='Sản lượng Qc lũy kế tháng')),
                ('cot_q', models.FloatField(blank=True, null=True, verbose_name='Đầu cực tháng')),
                ('cot_r', models.FloatField(blank=True, null=True, verbose_name='Thương phẩm tháng')),
                ('cot_s', models.FloatField(blank=True, null=True, verbose_name='Sản lượng Qc năm Ao giao')),
                ('cot_t', models.FloatField(blank=True, null=True, verbose_name='Sản lượng Qc lũy kế năm')),
                ('cot_u', models.FloatField(blank=True, null=True, verbose_name='Đầu cực năm')),
                ('cot_v', models.FloatField(blank=True, null=True, verbose_name='Thương phẩm năm')),
                ('cot_w', models.FloatField(blank=True, null=True, verbose_name='Sản lượng kế hoạch năm')),
                ('cot_x', models.FloatField(blank=True, null=True, verbose_name='Sản lượng tự dùng ngày')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thông số sản xuất',
                'verbose_name_plural': 'Thông số sản xuất',
                'ordering': ['-thoi_gian'],
                'unique_together': {('thoi_gian', 'nha_may')},
            },
        ),
        migrations.CreateModel(
            name='ThongsoGioPhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nha_may', models.CharField(default='songhinh', max_length=50)),
                ('ngay', models.DateField()),
                ('to_may', models.IntegerField()),
                ('gio_phat_dien', models.FloatField(blank=True, null=True)),
                ('gio_ngung', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thông số giờ phát',
                'verbose_name_plural': 'Thông số giờ phát',
                'ordering': ['-ngay', 'to_may'],
                'unique_together': {('ngay', 'to_may', 'nha_may')},
            },
        ),
    ]
