# Generated by Django 5.1 on 2026-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0004_thongsosanxuat_manual_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeUpdateState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_manual_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang thai cap nhat realtime',
                'verbose_name_plural': 'Trang thai cap nhat realtime',
            },
        ),
        migrations.CreateModel(
            name='SongHinhRealtimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('mntl', models.FloatField()),
                ('mnhl', models.FloatField()),
                ('ph1', models.FloatField()),
                ('ph2', models.FloatField()),
                ('pnm', models.FloatField()),
                ('qcm', models.FloatField()),
                ('dm1', models.FloatField()),
                ('dm2', models.FloatField()),
                ('dm3', models.FloatField()),
                ('dm4', models.FloatField()),
                ('dm5', models.FloatField()),
                ('dm6', models.FloatField()),
                ('qtran', models.FloatField()),
                ('dung_tich_ho', models.FloatField()),
                ('dung_tich_phong_lu', models.FloatField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Realtime Song Hinh',
                'verbose_name_plural': 'Realtime Song Hinh',
                'ordering': ['-time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='VinhSonRealtimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('mntla', models.FloatField()),
                ('mntla_td', models.FloatField()),
                ('mntlb', models.FloatField()),
                ('mntlc', models.FloatField()),
                ('mnhl', models.FloatField()),
                ('ph1', models.FloatField()),
                ('ph2', models.FloatField()),
                ('qcm', models.FloatField()),
                ('qtran', models.FloatField()),
                ('dung_tich_ho_a', models.FloatField()),
                ('dung_tich_ho_b', models.FloatField()),
                ('dung_tich_ho_c', models.FloatField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Realtime Vinh Son',
                'verbose_name_plural': 'Realtime Vinh Son',
                'ordering': ['-time_stamp'],
            },
        ),
    ]
