# Generated by Django 5.1 on 2026-05-08 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0005_realtimeupdatestate_songhinhrealtimesnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thongsogiophat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsogiophat_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thongsogiophat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsogiophat_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thongsosanxuat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsosanxuat_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thongsosanxuat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsosanxuat_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
