# Generated by Django 5.1 on 2026-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0006_thongsogiophat_created_by_thongsogiophat_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongsosanxuat',
            name='mucnuoc_gioihan_tuan_ho_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Mực nước giới hạn tuần hồ A'),
        ),
        migrations.AddField(
            model_name='thongsosanxuat',
            name='mucnuoc_gioihan_tuan_ho_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Mực nước giới hạn tuần hồ B'),
        ),
    ]
