# Generated by Django 5.1 on 2026-05-10 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0008_thongsosanxuat_vinhson_reservoir_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MucnuocQuytrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nha_may', models.CharField(default='songhinh', max_length=50)),
                ('ngay_bat_dau', models.CharField(help_text='Định dạng dd/MM, áp dụng cho tất cả các năm', max_length=5, verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.CharField(help_text='Định dạng dd/MM, áp dụng cho tất cả các năm', max_length=5, verbose_name='Ngày kết thúc')),
                ('muc_nuoc_bat_dau', models.FloatField(verbose_name='Mực nước hồ từ')),
                ('muc_nuoc_ket_thuc', models.FloatField(verbose_name='Mực nước hồ kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mucnuocquytrinh_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mucnuocquytrinh_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mực nước quy trình',
                'verbose_name_plural': 'Mực nước quy trình',
                'ordering': ['ngay_bat_dau', 'ngay_ket_thuc'],
                'unique_together': {('nha_may', 'ngay_bat_dau', 'ngay_ket_thuc')},
            },
        ),
    ]
