# Generated by Django 5.1 on 2026-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0010_mucnuocquytrinh_month_day_charfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramDoMuaVrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thoi_gian', models.DateTimeField(verbose_name='Thời gian')),
                ('Xa_Ea_M_doan', models.FloatField(blank=True, null=True, verbose_name="Xã Ea M'đoan")),
                ('Thon_10_Xa_Ea_M_Doal', models.FloatField(blank=True, null=True, verbose_name="Thôn 10 - Xã Ea M'Doal")),
                ('UBND_xa_Song_Hinh', models.FloatField(blank=True, null=True, verbose_name='UBND xã Sông Hinh')),
                ('Cu_Kroa', models.FloatField(blank=True, null=True, verbose_name='Cư Kroa')),
                ('Xa_Ea_Trang', models.FloatField(blank=True, null=True, verbose_name='Xã Ea Trang')),
                ('Dap_Tran', models.FloatField(blank=True, null=True, verbose_name='Đập Tràn')),
                ('Ho_B_TD_Vinh_Son', models.FloatField(blank=True, null=True, verbose_name='Hồ B - TĐ Vĩnh Sơn')),
                ('Ho_A_TD_Vinh_Son', models.FloatField(blank=True, null=True, verbose_name='Hồ A - TĐ Vĩnh Sơn')),
                ('Ho_C_TD_Vinh_Son', models.FloatField(blank=True, null=True, verbose_name='Hồ C - TĐ Vĩnh Sơn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trạm đo mưa Vrain',
                'verbose_name_plural': 'Trạm đo mưa Vrain',
                'ordering': ['-Thoi_gian'],
            },
        ),
    ]
