# Generated by Django 5.1 on 2026-05-25 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0014_realtimeupdatestate_last_hourly_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongSoThuyVanCaiDat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nha_may', models.CharField(default='songhinh', max_length=50)),
                ('nam', models.PositiveIntegerField()),
                ('loai', models.CharField(choices=[('annual', 'Ke hoach nam'), ('monthly', 'Ke hoach thang'), ('weekly', 'MNGH tuan')], max_length=20)),
                ('thang', models.PositiveSmallIntegerField(default=0)),
                ('tuan', models.PositiveSmallIntegerField(default=0)),
                ('tuan_bat_dau', models.DateField(blank=True, null=True)),
                ('tuan_ket_thuc', models.DateField(blank=True, null=True)),
                ('sanluong_kehoach_nam', models.FloatField(blank=True, null=True)),
                ('sanluong_kehoach_thang', models.FloatField(blank=True, null=True)),
                ('mucnuoc_gioihan_tuan', models.FloatField(blank=True, null=True)),
                ('mucnuoc_gioihan_tuan_ho_a', models.FloatField(blank=True, null=True)),
                ('mucnuoc_gioihan_tuan_ho_b', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsothuyvancaidat_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsothuyvancaidat_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thong so thuy van cai dat',
                'verbose_name_plural': 'Thong so thuy van cai dat',
                'ordering': ['nha_may', 'nam', 'loai', 'thang', 'tuan'],
                'unique_together': {('nha_may', 'nam', 'loai', 'thang', 'tuan')},
            },
        ),
    ]
