# Generated by Django 3.2.25 on 2026-06-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thongsothuyvan', '0016_dashboard_query_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongSoThuyVanThucTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nha_may', models.CharField(max_length=50)),
                ('ngay', models.DateField()),
                ('muc_nuoc_ho', models.FloatField(blank=True, null=True)),
                ('qve', models.FloatField(blank=True, null=True)),
                ('muc_nuoc_ho_a', models.FloatField(blank=True, null=True)),
                ('muc_nuoc_ho_b', models.FloatField(blank=True, null=True)),
                ('muc_nuoc_ho_c', models.FloatField(blank=True, null=True)),
                ('qve_ho_a', models.FloatField(blank=True, null=True)),
                ('qve_ho_b', models.FloatField(blank=True, null=True)),
                ('qve_ho_c', models.FloatField(blank=True, null=True)),
                ('qve_tong', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsothuyvanthucte_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thongsothuyvanthucte_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thong so thuy van thuc te',
                'verbose_name_plural': 'Thong so thuy van thuc te',
                'ordering': ['-ngay', 'nha_may'],
            },
        ),
        migrations.AddIndex(
            model_name='thongsothuyvanthucte',
            index=models.Index(fields=['nha_may', '-ngay'], name='tstt_plant_day_desc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thongsothuyvanthucte',
            unique_together={('nha_may', 'ngay')},
        ),
    ]
