# Generated by Django 3.2.25 on 2026-06-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0017_add_thongso_thuyvan_thucte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thongsothuyvanthucte',
            options={'ordering': ['-ngay', 'nha_may'], 'verbose_name': 'Thủy văn theo dõi', 'verbose_name_plural': 'Thủy văn theo dõi'},
        ),
    ]
