# Generated by Django 3.2.25 on 2026-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongsothuyvan', '0018_rename_thuc_te_admin_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songhinhmnh',
            name='Mucnuoc',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='songhinhmnh',
            name='dungtich',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='thuongkontummnh',
            name='Mucnuoc',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='thuongkontummnh',
            name='dungtich',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vinhson_hoa',
            name='Mucnuoc',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='vinhson_hoa',
            name='dungtich',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vinhson_hob',
            name='Mucnuoc',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='vinhson_hob',
            name='dungtich',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vinhson_hoc',
            name='Mucnuoc',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='vinhson_hoc',
            name='dungtich',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
