# Generated by Django 3.2.25 on 2025-09-27 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bang_de_nghi_nhap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stt', models.IntegerField()),
                ('ma_bravo_text', models.CharField(blank=True, max_length=100)),
                ('ten_vat_tu', models.CharField(max_length=255)),
                ('don_vi', models.CharField(max_length=50)),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.BigIntegerField(default=0)),
                ('thanh_tien', models.BigIntegerField(default=0)),
                ('so_de_nghi_cap', models.CharField(blank=True, max_length=50)),
                ('ngay_de_nghi', models.DateTimeField()),
                ('bo_phan', models.CharField(blank=True, max_length=100)),
                ('ghi_chu', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Đề nghị nhập',
                'verbose_name_plural': 'Đề nghị nhập',
            },
        ),
        migrations.CreateModel(
            name='Bang_de_nghi_xuat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stt', models.IntegerField()),
                ('ma_bravo_text', models.CharField(blank=True, max_length=100)),
                ('ten_vat_tu', models.CharField(max_length=255)),
                ('don_vi', models.CharField(max_length=50)),
                ('so_luong', models.IntegerField()),
                ('ngay_de_nghi_xuat', models.DateTimeField()),
                ('ghi_chu', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Đề nghị xuất',
                'verbose_name_plural': 'Đề nghị xuất',
            },
        ),
        migrations.CreateModel(
            name='Bang_hinh_anh_vat_tu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hinh_anh', models.ImageField(help_text='Hình ảnh vật tư', upload_to='vat_tu/images/')),
                ('mo_ta', models.CharField(blank=True, help_text='Mô tả hình ảnh (tùy chọn)', max_length=255, null=True)),
                ('thu_tu', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị hình ảnh')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hình ảnh vật tư',
                'verbose_name_plural': 'Hình ảnh vật tư',
                'ordering': ['thu_tu', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bang_kiem_ke',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('so_thu_tu', models.IntegerField()),
                ('ma_bravo', models.CharField(default='', help_text='Mã Bravo để so sánh với bảng vật tư', max_length=100)),
                ('ma_nha_may', models.CharField(default='', help_text='Mã nhà máy để so sánh với bảng vật tư', max_length=20)),
                ('ten_vat_tu', models.CharField(max_length=255)),
                ('don_vi', models.CharField(max_length=50)),
                ('so_luong', models.IntegerField(help_text='Số lượng kiểm kê (dự kiến)')),
                ('so_luong_thuc_te', models.IntegerField(default=0, help_text='Số lượng thực tế khi kiểm kê')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'verbose_name_plural': 'Phiếu kiểm kê',
            },
        ),
        migrations.CreateModel(
            name='Bang_nha_may',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ma_nha_may', models.CharField(max_length=50, unique=True)),
                ('ten_nha_may', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nhà máy',
                'verbose_name_plural': 'Nhà máy',
            },
        ),
        migrations.CreateModel(
            name='Bang_vat_tu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ten_vat_tu', models.CharField(max_length=255)),
                ('don_vi', models.CharField(max_length=50)),
                ('thong_so_ky_thuat', models.CharField(blank=True, max_length=500, null=True)),
                ('ma_bravo', models.CharField(db_index=True, max_length=100)),
                ('ton_kho', models.IntegerField(default=0)),
                ('so_luong_kh', models.IntegerField(default=0)),
                ('ma_QR', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('hinh_anh_vt', models.ImageField(blank=True, null=True, upload_to='vat_tu/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vật tư',
                'verbose_name_plural': 'Vật tư',
            },
        ),
        migrations.CreateModel(
            name='Bang_vi_tri',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ma_vi_tri', models.CharField(max_length=50, unique=True)),
                ('ma_he_thong', models.CharField(max_length=100)),
                ('kho', models.CharField(max_length=20)),
                ('ke', models.CharField(max_length=20)),
                ('ngan', models.CharField(max_length=20)),
                ('tang', models.CharField(max_length=20)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Vị trí kho',
                'verbose_name_plural': 'Vị trí kho',
            },
        ),
        migrations.CreateModel(
            name='Bang_xuat_xu',
            fields=[
                ('ma_country', models.CharField(help_text='Mã country (VIE, USA, KOR, etc.)', max_length=10, primary_key=True, serialize=False)),
                ('ten_nuoc', models.CharField(help_text='Tên nước đầy đủ', max_length=100)),
                ('ten_viet_tat', models.CharField(blank=True, help_text='Tên viết tắt', max_length=50, null=True)),
                ('mo_ta', models.TextField(blank=True, help_text='Mô tả thêm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xuất xứ',
                'verbose_name_plural': 'Danh sách xuất xứ',
                'db_table': 'bang_xuat_xu',
            },
        ),
        migrations.AddIndex(
            model_name='bang_vi_tri',
            index=models.Index(fields=['ma_vi_tri'], name='khovattu_ba_ma_vi_t_a146f7_idx'),
        ),
        migrations.AddField(
            model_name='bang_vat_tu',
            name='bang_nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_tu', to='khovattu.bang_nha_may'),
        ),
        migrations.AddField(
            model_name='bang_vat_tu',
            name='ma_vi_tri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_tu', to='khovattu.bang_vi_tri'),
        ),
        migrations.AddField(
            model_name='bang_vat_tu',
            name='xuat_xu',
            field=models.ForeignKey(blank=True, help_text='Xuất xứ vật tư (tự động map từ mã Bravo)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_tu', to='khovattu.bang_xuat_xu'),
        ),
        migrations.AddField(
            model_name='bang_kiem_ke',
            name='vat_tu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kiem_ke', to='khovattu.bang_vat_tu'),
        ),
        migrations.AddField(
            model_name='bang_hinh_anh_vat_tu',
            name='vat_tu',
            field=models.ForeignKey(help_text='Vật tư liên kết', on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh_list', to='khovattu.bang_vat_tu'),
        ),
        migrations.AddField(
            model_name='bang_de_nghi_xuat',
            name='vat_tu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='de_nghi_xuat', to='khovattu.bang_vat_tu'),
        ),
        migrations.AddField(
            model_name='bang_de_nghi_nhap',
            name='vat_tu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='de_nghi_nhap', to='khovattu.bang_vat_tu'),
        ),
        migrations.AddIndex(
            model_name='bang_vat_tu',
            index=models.Index(fields=['ten_vat_tu'], name='khovattu_ba_ten_vat_478ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='bang_vat_tu',
            index=models.Index(fields=['ma_bravo'], name='khovattu_ba_ma_brav_3b2b72_idx'),
        ),
        migrations.AddConstraint(
            model_name='bang_vat_tu',
            constraint=models.UniqueConstraint(fields=('bang_nha_may', 'ma_bravo'), name='uniq_vattu_nhamay_mabravo'),
        ),
        migrations.AddConstraint(
            model_name='bang_vat_tu',
            constraint=models.CheckConstraint(check=models.Q(('ton_kho__gte', 0)), name='chk_vattu_ton_kho_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bang_vat_tu',
            constraint=models.CheckConstraint(check=models.Q(('so_luong_kh__gte', 0)), name='chk_vattu_so_luong_kh_gte_0'),
        ),
        migrations.AddIndex(
            model_name='bang_hinh_anh_vat_tu',
            index=models.Index(fields=['vat_tu', 'thu_tu'], name='khovattu_ba_vat_tu__19a190_idx'),
        ),
        migrations.AddIndex(
            model_name='bang_hinh_anh_vat_tu',
            index=models.Index(fields=['vat_tu', 'is_active'], name='khovattu_ba_vat_tu__9461eb_idx'),
        ),
    ]
