# Generated by Django 5.1 on 2025-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bang_de_nghi_nhap',
            name='nguoi_de_nghi',
            field=models.CharField(blank=True, help_text='Người đề nghị nhập', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bang_de_nghi_xuat',
            name='nguoi_de_nghi',
            field=models.CharField(blank=True, help_text='Người đề nghị xuất', max_length=255, null=True),
        ),
    ]
