# Generated by Django 3.2.25 on 2025-10-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255, verbose_name='Tên')),
                ('ma', models.CharField(max_length=100, verbose_name='Mã cấp hiện tại')),
                ('ma_day_du', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Mã đầy đủ')),
                ('loai', models.CharField(blank=True, max_length=32, verbose_name='Loại/Phân loại')),
                ('trang_thai', models.CharField(blank=True, max_length=32, verbose_name='Trạng thái')),
                ('nha_che_tao', models.CharField(blank=True, max_length=255, verbose_name='Nhà chế tạo')),
                ('nha_cung_cap', models.CharField(blank=True, max_length=255, verbose_name='Nhà cung cấp')),
                ('nuoc_san_xuat', models.CharField(blank=True, max_length=64, verbose_name='Nước sản xuất')),
                ('nha_may', models.CharField(blank=True, max_length=64, verbose_name='Nhà máy/khu vực')),
                ('do_uu_tien', models.PositiveSmallIntegerField(default=0, verbose_name='Mức ưu tiên')),
                ('so_serial', models.CharField(blank=True, max_length=128, verbose_name='Số S/N')),
                ('mo_ta_ky_thuat', models.TextField(blank=True, verbose_name='Thông số kỹ thuật (text)')),
                ('cap', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Cấp')),
                ('thu_tu', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con', to='quanlyvanhanh.thietbi', verbose_name='Thiết bị cha')),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
                'db_table': 'thiet_bi',
                'ordering': ['cha__id', 'thu_tu', 'ten'],
            },
        ),
        migrations.CreateModel(
            name='VatTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_vat_tu', models.CharField(max_length=100, unique=True, verbose_name='Mã vật tư')),
                ('ten_vat_tu', models.CharField(max_length=255, verbose_name='Tên vật tư')),
                ('don_vi_tinh', models.CharField(blank=True, max_length=32, verbose_name='Đơn vị tính')),
                ('quy_cach', models.CharField(blank=True, max_length=255, verbose_name='Quy cách/Mô tả')),
                ('nha_che_tao', models.CharField(blank=True, max_length=255, verbose_name='Nhà chế tạo')),
                ('nha_cung_cap', models.CharField(blank=True, max_length=255, verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Vật tư',
                'verbose_name_plural': 'Vật tư',
                'db_table': 'vat_tu',
            },
        ),
        migrations.CreateModel(
            name='ThongSoVanHanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thong_so', models.CharField(max_length=128, verbose_name='Tên thông số')),
                ('gia_tri', models.CharField(blank=True, max_length=255, verbose_name='Giá trị')),
                ('don_vi', models.CharField(blank=True, max_length=32, verbose_name='Đơn vị')),
                ('gia_tri_toi_thieu', models.CharField(blank=True, max_length=64, verbose_name='Min')),
                ('gia_tri_toi_da', models.CharField(blank=True, max_length=64, verbose_name='Max')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyvanhanh.thietbi', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Thông số vận hành',
                'verbose_name_plural': 'Thông số vận hành',
                'db_table': 'thong_so_van_hanh',
            },
        ),
        migrations.CreateModel(
            name='ThietBiVatTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Số lượng')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyvanhanh.thietbi', verbose_name='Thiết bị')),
                ('vat_tu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyvanhanh.vattu', verbose_name='Vật tư')),
            ],
            options={
                'verbose_name': 'Vật tư gắn với thiết bị',
                'verbose_name_plural': 'Vật tư gắn với thiết bị',
                'db_table': 'thiet_bi_vat_tu',
            },
        ),
        migrations.CreateModel(
            name='DinhKem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('tep', models.FileField(blank=True, null=True, upload_to='dinh_kem/', verbose_name='Tệp')),
                ('duong_dan', models.URLField(blank=True, verbose_name='URL')),
                ('dinh_dang', models.CharField(blank=True, max_length=64, verbose_name='MIME/Định dạng')),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyvanhanh.thietbi', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Đính kèm',
                'verbose_name_plural': 'Đính kèm',
                'db_table': 'dinh_kem',
            },
        ),
        migrations.CreateModel(
            name='AnToanThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moi_nguy', models.CharField(max_length=255, verbose_name='Mối nguy')),
                ('bien_phap', models.TextField(blank=True, verbose_name='Biện pháp')),
                ('bao_ho_lao_dong', models.CharField(blank=True, max_length=255, verbose_name='PPE')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyvanhanh.thietbi', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'An toàn thiết bị',
                'verbose_name_plural': 'An toàn thiết bị',
                'db_table': 'an_toan_thiet_bi',
            },
        ),
        migrations.AddConstraint(
            model_name='thongsovanhanh',
            constraint=models.UniqueConstraint(fields=('thiet_bi', 'ten_thong_so'), name='uq_tsvh_ten'),
        ),
        migrations.AddConstraint(
            model_name='thietbivattu',
            constraint=models.UniqueConstraint(fields=('thiet_bi', 'vat_tu'), name='uq_tb_vt'),
        ),
        migrations.AddIndex(
            model_name='thietbi',
            index=models.Index(fields=['cha', 'thu_tu'], name='thiet_bi_cha_id_34063a_idx'),
        ),
        migrations.AddIndex(
            model_name='thietbi',
            index=models.Index(fields=['cap', 'ten'], name='thiet_bi_cap_e5454b_idx'),
        ),
        migrations.AddConstraint(
            model_name='thietbi',
            constraint=models.UniqueConstraint(fields=('cha', 'ma'), name='uq_thietbi_cha_ma'),
        ),
    ]
