# Generated by Django 3.2.25 on 2025-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='ngay_dua_vao_van_hanh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đưa vào vận hành'),
        ),
        migrations.AddField(
            model_name='thietbi',
            name='ngay_lap_dat',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt'),
        ),
    ]
