# Generated by Django 3.2.25 on 2025-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0002_auto_20251009_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='mo_ta_ky_thuat',
            field=models.TextField(blank=True, null=True, verbose_name='Thông số kỹ thuật (text)'),
        ),
    ]
