# Generated by Django 3.2.25 on 2025-10-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0003_alter_thietbi_mo_ta_ky_thuat'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='thiet_bi/', verbose_name='Hình ảnh thiết bị'),
        ),
    ]
