# Generated by Django 5.1 on 2025-10-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0004_thietbi_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='so_serial',
            field=models.CharField(blank=True, max_length=255, verbose_name='Số S/N'),
        ),
    ]
