# Generated by Django 3.2.25 on 2025-10-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0005_update_so_serial_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='bo_phan_quan_ly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bộ phận quản lý'),
        ),
        migrations.AddField(
            model_name='thietbi',
            name='ma_van_hanh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã vận hành'),
        ),
    ]
