# Generated by Django 3.2.25 on 2025-10-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0006_add_ma_van_hanh_bo_phan_quan_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='bang_ve',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bảng vẽ'),
        ),
    ]
