# Generated by Django 3.2.25 on 2025-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0007_add_bang_ve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='loai',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại/Phân loại'),
        ),
    ]
