# Generated by Django 5.1 on 2025-10-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0008_update_loai_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangThongSoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mau', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('loai_thiet_bi', models.CharField(max_length=100, verbose_name='Loại thiết bị')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Mẫu bảng thông số',
                'verbose_name_plural': 'Mẫu bảng thông số',
                'db_table': 'bang_thong_so_template',
                'ordering': ['loai_thiet_bi', 'ten_mau'],
            },
        ),
        migrations.CreateModel(
            name='BangThongSoTemplateChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_thong_so', models.CharField(max_length=50, verbose_name='Mã thông số')),
                ('ten_thong_so', models.CharField(max_length=255, verbose_name='Tên thông số')),
                ('ky_hieu', models.CharField(blank=True, max_length=20, verbose_name='Ký hiệu')),
                ('don_vi', models.CharField(blank=True, max_length=32, verbose_name='Đơn vị')),
                ('gia_tri_toi_thieu', models.CharField(blank=True, max_length=64, verbose_name='Giá trị tối thiểu')),
                ('gia_tri_toi_da', models.CharField(blank=True, max_length=64, verbose_name='Giá trị tối đa')),
                ('thu_tu', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanlyvanhanh.bangthongsotemplate', verbose_name='Mẫu bảng thông số')),
            ],
            options={
                'verbose_name': 'Chi tiết mẫu bảng thông số',
                'verbose_name_plural': 'Chi tiết mẫu bảng thông số',
                'db_table': 'bang_thong_so_template_chi_tiet',
                'ordering': ['template', 'thu_tu', 'ma_thong_so'],
                'constraints': [models.UniqueConstraint(fields=('template', 'ma_thong_so'), name='uq_btsct_ma')],
            },
        ),
    ]
