# Generated by Django 3.2.25 on 2025-10-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0009_bangthongsotemplate_bangthongsotemplatechitiet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='don_vi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Đơn vị tính'),
        ),
        migrations.DeleteModel(
            name='BangThongSoTemplateChiTiet',
        ),
        migrations.DeleteModel(
            name='BangThongSoTemplate',
        ),
    ]
