# Generated by Django 3.2.25 on 2025-10-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0010_auto_20251018_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='don_vi',
            field=models.CharField(blank=True, max_length=32, verbose_name='Đơn vị'),
        ),
    ]
