# Generated by Django 5.1 on 2025-10-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0011_alter_thongsovanhanh_don_vi'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongsovanhanh',
            name='ma_thong_so',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã thông số vận hành'),
        ),
        migrations.AddField(
            model_name='thongsovanhanh',
            name='nha_may',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nhà máy'),
        ),
    ]
