# Generated by Django 5.1 on 2025-10-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0012_thongsovanhanh_ma_thong_so_thongsovanhanh_nha_may'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongsovanhanh',
            name='gia_tri_thiet_ke',
            field=models.CharField(blank=True, max_length=64, verbose_name='Giá trị thiết kế'),
        ),
        migrations.AddField(
            model_name='thongsovanhanh',
            name='ky_hieu_van_hanh',
            field=models.CharField(blank=True, max_length=32, verbose_name='Ký hiệu vận hành'),
        ),
    ]
