# Generated by Django 5.1 on 2025-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0013_thongsovanhanh_gia_tri_thiet_ke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='gia_tri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá trị'),
        ),
    ]
