# Generated by Django 3.2.25 on 2025-10-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0014_alter_thongsovanhanh_gia_tri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='gia_tri_thiet_ke',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Giá trị thiết kế'),
        ),
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='gia_tri_toi_da',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='gia_tri_toi_thieu',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Min'),
        ),
    ]
