# Generated by Django 5.1 on 2025-10-18 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0015_auto_20251018_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongsovanhanh',
            name='ngay_nhap',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nhập thông số'),
        ),
        migrations.AddField(
            model_name='thongsovanhanh',
            name='thoi_diem_nhap',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm nhập thông số'),
        ),
    ]
