# Generated by Django 3.2.25 on 2025-10-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0016_thongsovanhanh_ngay_nhap_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='thongsovanhanh',
            name='uq_tsvh_ten',
        ),
        migrations.AddConstraint(
            model_name='thongsovanhanh',
            constraint=models.UniqueConstraint(fields=('thiet_bi', 'ten_thong_so', 'thoi_diem_nhap'), name='uq_tsvh_tb_ten_time'),
        ),
    ]
