# Generated by Django 3.2.25 on 2025-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0017_auto_20251020_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='ngay_nhap',
            field=models.DateField(verbose_name='Ngày nhập thông số'),
        ),
        migrations.AlterField(
            model_name='thongsovanhanh',
            name='thoi_diem_nhap',
            field=models.DateTimeField(verbose_name='Thời điểm nhập thông số'),
        ),
    ]
