# Generated by Django 3.2.25 on 2025-10-28 02:58

from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Concat
from datetime import datetime, time
import pytz


def convert_time_to_datetime(apps, schema_editor):
    """
    Convert TimeField to DateTimeField by combining ngay_nhap + thoi_diem_nhap
    """
    ThongSoToMay = apps.get_model('quanlyvanhanh', 'ThongSoToMay')

    # Get Vietnam timezone
    vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')

    # Process all records
    for record in ThongSoToMay.objects.all():
        if record.thoi_diem_nhap and record.ngay_nhap:
            # Combine date and time
            naive_datetime = datetime.combine(record.ngay_nhap, record.thoi_diem_nhap)
            # Localize to Vietnam timezone
            localized_datetime = vietnam_tz.localize(naive_datetime)
            # Update the record
            record.thoi_diem_nhap_new = localized_datetime
            record.save(update_fields=['thoi_diem_nhap_new'])


def reverse_datetime_to_time(apps, schema_editor):
    """
    Reverse: Convert DateTimeField back to TimeField
    """
    ThongSoToMay = apps.get_model('quanlyvanhanh', 'ThongSoToMay')

    for record in ThongSoToMay.objects.all():
        if record.thoi_diem_nhap_new:
            # Extract time part
            record.thoi_diem_nhap = record.thoi_diem_nhap_new.time()
            record.save(update_fields=['thoi_diem_nhap'])


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0019_auto_20251025_0623'),
    ]

    operations = [
        # Step 1: Add new DateTimeField column
        migrations.AddField(
            model_name='thongsotomay',
            name='thoi_diem_nhap_new',
            field=models.DateTimeField(null=True, blank=True, verbose_name='Thời điểm nhập (New)'),
        ),

        # Step 2: Convert data from TimeField to DateTimeField
        migrations.RunPython(
            convert_time_to_datetime,
            reverse_datetime_to_time,
        ),

        # Step 2.5: Drop constraints/indexes that reference old thoi_diem_nhap.
        # SQLite validates indexes while dropping a column, so they must go first.
        migrations.AlterUniqueTogether(
            name='thongsotomay',
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name='thongsotomay',
            name='thong_so_to_ngay_nh_1a2753_idx',
        ),
        migrations.RemoveIndex(
            model_name='thongsotomay',
            name='thong_so_to_thiet_b_4d1fd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='thongsotomay',
            name='thong_so_to_ten_tho_306c4b_idx',
        ),

        # Step 3: Remove old TimeField column
        migrations.RemoveField(
            model_name='thongsotomay',
            name='thoi_diem_nhap',
        ),

        # Step 4: Rename new field to original name
        migrations.RenameField(
            model_name='thongsotomay',
            old_name='thoi_diem_nhap_new',
            new_name='thoi_diem_nhap',
        ),

        # Step 5: Update field properties
        migrations.AlterField(
            model_name='thongsotomay',
            name='thoi_diem_nhap',
            field=models.DateTimeField(verbose_name='Thời điểm nhập'),
        ),

        # Step 6: Recreate final indexes/unique constraint against the DateTimeField.
        migrations.AddIndex(
            model_name='thongsotomay',
            index=models.Index(fields=['ngay_nhap', 'thoi_diem_nhap'], name='thong_so_to_ngay_nh_1a2753_idx'),
        ),
        migrations.AddIndex(
            model_name='thongsotomay',
            index=models.Index(fields=['thiet_bi', 'ngay_nhap'], name='thong_so_to_thiet_b_4d1fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='thongsotomay',
            index=models.Index(fields=['ten_thong_so', 'ngay_nhap'], name='thong_so_to_ten_tho_306c4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thongsotomay',
            unique_together={('thiet_bi', 'ten_thong_so', 'thoi_diem_nhap', 'ngay_nhap')},
        ),
    ]
