# Generated by Django 3.2.25 on 2026-06-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0020_convert_thoi_diem_nhap_to_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongSoTram110KV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thong_so', models.CharField(max_length=255, verbose_name='Tên thông số')),
                ('ma_thong_so', models.CharField(max_length=100, verbose_name='Mã thông số')),
                ('don_vi', models.CharField(max_length=50, verbose_name='Đơn vị')),
                ('nha_may', models.CharField(max_length=64, verbose_name='Nhà máy')),
                ('ky_hieu_van_hanh', models.CharField(blank=True, max_length=100, verbose_name='Ký hiệu vận hành')),
                ('gia_tri', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá trị')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('thoi_diem_nhap', models.DateTimeField(verbose_name='Thời điểm nhập')),
                ('ngay_nhap', models.DateField(verbose_name='Ngày nhập')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyvanhanh.thietbi', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Thông số trạm 110kV',
                'verbose_name_plural': 'Thông số trạm 110kV',
                'db_table': 'thong_so_tram_110kv',
            },
        ),
        migrations.AddIndex(
            model_name='thongsotram110kv',
            index=models.Index(fields=['ngay_nhap', 'thoi_diem_nhap'], name='thong_so_tr_ngay_nh_c54236_idx'),
        ),
        migrations.AddIndex(
            model_name='thongsotram110kv',
            index=models.Index(fields=['thiet_bi', 'ngay_nhap'], name='thong_so_tr_thiet_b_b1709b_idx'),
        ),
        migrations.AddIndex(
            model_name='thongsotram110kv',
            index=models.Index(fields=['ten_thong_so', 'ngay_nhap'], name='thong_so_tr_ten_tho_2c69a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thongsotram110kv',
            unique_together={('thiet_bi', 'ten_thong_so', 'thoi_diem_nhap', 'ngay_nhap')},
        ),
    ]
