# Generated by Django 3.2.25 on 2026-06-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0021_auto_20260607_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguongThongSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nha_may', models.CharField(blank=True, max_length=64, verbose_name='Nhà máy')),
                ('ma_thong_so', models.CharField(db_index=True, max_length=100, verbose_name='Mã thông số')),
                ('ten_thong_so', models.CharField(blank=True, max_length=255, verbose_name='Tên thông số')),
                ('don_vi', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('alarm', models.FloatField(blank=True, null=True, verbose_name='Ngưỡng cảnh báo (Alarm)')),
                ('trip', models.FloatField(blank=True, null=True, verbose_name='Ngưỡng sự cố (Trip)')),
                ('rated', models.FloatField(blank=True, null=True, verbose_name='Giá trị định mức (Rated)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('thiet_bi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nguong_thong_so', to='quanlyvanhanh.thietbi', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Ngưỡng thông số',
                'verbose_name_plural': 'Ngưỡng thông số',
                'db_table': 'nguong_thong_so',
                'unique_together': {('nha_may', 'thiet_bi', 'ma_thong_so')},
            },
        ),
    ]
