# Generated by Django 3.2.25 on 2026-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0022_nguongthongso'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguongthongso',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị lớn nhất (Max)'),
        ),
        migrations.AddField(
            model_name='nguongthongso',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị nhỏ nhất (Min)'),
        ),
    ]
