# Generated by Django 3.2.25 on 2026-06-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanhanh', '0023_auto_20260609_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsotomay',
            name='gia_tri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá trị'),
        ),
    ]
