# Generated by Django 3.2.25 on 2026-06-11 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quanlyvanhanh', '0024_alter_thongsotomay_gia_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongsotomay',
            name='nguoi_nhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thongsotomay_nhap', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập'),
        ),
        migrations.AddField(
            model_name='thongsotram110kv',
            name='nguoi_nhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thongsotram_nhap', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập'),
        ),
        migrations.AddField(
            model_name='thongsovanhanh',
            name='nguoi_nhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thongsovanhanh_nhap', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập'),
        ),
    ]
