# Generated by Django 5.2.17 on 2026-08-24 08:42

import django.db.models.deletion
import quanlycatruc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KipTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loai_kip', models.CharField(choices=[('van_hanh', 'Vận hành'), ('hanh_chinh', 'Kỹ thuật - hành chính')], max_length=20)),
                ('ma_kip', models.CharField(choices=[('A', 'Kíp A'), ('B', 'Kíp B'), ('C', 'Kíp C'), ('D', 'Kíp D'), ('HC1', 'Ca 1'), ('HC2', 'Ca 2')], max_length=3)),
                ('ten_kip', models.CharField(max_length=80)),
                ('mau_nhan_dien', models.CharField(default='#4f46e5', max_length=20)),
                ('thu_tu', models.PositiveSmallIntegerField(default=1)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_kip_truc', to='khovattu.bang_nha_may')),
            ],
            options={
                'verbose_name': 'Kíp trực',
                'verbose_name_plural': 'Các kíp trực',
                'ordering': ['nha_may', 'loai_kip', 'thu_tu', 'ma_kip'],
            },
        ),
        migrations.CreateModel(
            name='LichTrucCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thang', models.PositiveSmallIntegerField()),
                ('nam', models.PositiveIntegerField()),
                ('phien_ban', models.PositiveIntegerField(default=1)),
                ('trang_thai', models.CharField(choices=[('du_thao', 'Dự thảo'), ('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('dang_ap_dung', 'Đang áp dụng'), ('da_khoa', 'Đã khóa'), ('tu_choi', 'Từ chối')], default='du_thao', max_length=20)),
                ('ngay_gui_duyet', models.DateTimeField(blank=True, null=True)),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True)),
                ('ly_do_tu_choi', models.TextField(blank=True)),
                ('ghi_chu', models.TextField(blank=True)),
                ('snapshot_nhan_su', models.JSONField(blank=True, default=dict)),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lich_truc_ca_da_duyet', to=settings.AUTH_USER_MODEL)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_truc_ca_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_truc_ca', to='khovattu.bang_nha_may')),
            ],
            options={
                'verbose_name': 'Lịch trực ca tháng',
                'verbose_name_plural': 'Lịch trực ca tháng',
                'ordering': ['-nam', '-thang', 'nha_may', '-phien_ban'],
            },
        ),
        migrations.CreateModel(
            name='LichSuLichTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(max_length=40)),
                ('du_lieu_truoc', models.JSONField(blank=True, default=dict)),
                ('du_lieu_sau', models.JSONField(blank=True, default=dict)),
                ('ly_do', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thuc_hien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lich_truc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='quanlycatruc.lichtrucca')),
            ],
            options={
                'verbose_name': 'Lịch sử lịch trực',
                'verbose_name_plural': 'Lịch sử lịch trực',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MauChuKyCaTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ten_mau', models.CharField(max_length=150)),
                ('ngay_moc_van_hanh', models.DateField()),
                ('vi_tri_moc_van_hanh', models.PositiveSmallIntegerField(default=0)),
                ('ngay_moc_hanh_chinh', models.DateField()),
                ('vi_tri_moc_hanh_chinh', models.PositiveSmallIntegerField(default=0)),
                ('chu_ky_van_hanh', models.JSONField(default=quanlycatruc.models.default_operation_cycle)),
                ('chu_ky_hanh_chinh', models.JSONField(default=quanlycatruc.models.default_admin_cycle)),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField(blank=True, null=True)),
                ('phien_ban', models.PositiveIntegerField(default=1)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_chu_ky_ca_truc', to='khovattu.bang_nha_may')),
            ],
            options={
                'verbose_name': 'Mẫu chu kỳ ca trực',
                'verbose_name_plural': 'Mẫu chu kỳ ca trực',
                'ordering': ['-tu_ngay', '-phien_ban'],
            },
        ),
        migrations.AddField(
            model_name='lichtrucca',
            name='mau_chu_ky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_da_sinh', to='quanlycatruc.mauchukycatruc'),
        ),
        migrations.CreateModel(
            name='NgayTrucCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay', models.DateField()),
                ('la_ngay_chuyen_kip', models.BooleanField(default=False)),
                ('la_ngay_chuyen_ca_hc', models.BooleanField(default=False)),
                ('da_dieu_chinh', models.BooleanField(default=False)),
                ('ly_do_dieu_chinh', models.TextField(blank=True)),
                ('ghi_chu', models.TextField(blank=True)),
                ('kip_ca_dem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_ca_dem', to='quanlycatruc.kiptruc')),
                ('kip_ca_ngay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_ca_ngay', to='quanlycatruc.kiptruc')),
                ('kip_hanh_chinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_ca_hanh_chinh', to='quanlycatruc.kiptruc')),
                ('kip_hanh_chinh_truoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cac_lan_giao_ca_hanh_chinh', to='quanlycatruc.kiptruc')),
                ('lich_truc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_ngay', to='quanlycatruc.lichtrucca')),
            ],
            options={
                'verbose_name': 'Ngày trực ca',
                'verbose_name_plural': 'Các ngày trực ca',
                'ordering': ['ngay'],
            },
        ),
        migrations.CreateModel(
            name='ThanhVienKipTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vai_tro', models.CharField(choices=[('truong_ca', 'Trưởng ca'), ('truc_chinh', 'Trực chính'), ('truc_phu', 'Trực phụ'), ('ky_thuat_vien', 'Kỹ thuật viên'), ('nhan_vien', 'Nhân viên')], default='nhan_vien', max_length=20)),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField(blank=True, null=True)),
                ('thu_tu_hien_thi', models.PositiveSmallIntegerField(default=1)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
                ('kip_truc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien', to='quanlycatruc.kiptruc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phan_cong_kip_truc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thành viên kíp trực',
                'verbose_name_plural': 'Thành viên kíp trực',
                'ordering': ['kip_truc', 'thu_tu_hien_thi', 'tu_ngay'],
            },
        ),
        migrations.AddConstraint(
            model_name='kiptruc',
            constraint=models.UniqueConstraint(fields=('nha_may', 'ma_kip'), name='uq_catruc_nhamay_makip'),
        ),
        migrations.AddConstraint(
            model_name='kiptruc',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loai_kip', 'van_hanh'), ('ma_kip__in', ['A', 'B', 'C', 'D'])), models.Q(('loai_kip', 'hanh_chinh'), ('ma_kip__in', ['HC1', 'HC2'])), _connector='OR'), name='ck_catruc_loai_ma_hop_le'),
        ),
        migrations.AddConstraint(
            model_name='mauchukycatruc',
            constraint=models.UniqueConstraint(fields=('nha_may', 'phien_ban'), name='uq_mauchuky_nhamay_phienban'),
        ),
        migrations.AddConstraint(
            model_name='lichtrucca',
            constraint=models.UniqueConstraint(fields=('nha_may', 'nam', 'thang', 'phien_ban'), name='uq_lichtruc_thang_phienban'),
        ),
        migrations.AddConstraint(
            model_name='lichtrucca',
            constraint=models.CheckConstraint(condition=models.Q(('thang__gte', 1), ('thang__lte', 12)), name='ck_lichtruc_thang'),
        ),
        migrations.AddConstraint(
            model_name='ngaytrucca',
            constraint=models.UniqueConstraint(fields=('lich_truc', 'ngay'), name='uq_ngaytruc_lich_ngay'),
        ),
        migrations.AddIndex(
            model_name='thanhvienkiptruc',
            index=models.Index(fields=['user', 'tu_ngay', 'den_ngay'], name='quanlycatru_user_id_64edd5_idx'),
        ),
    ]
