# Generated by Django 5.2.17 on 2026-08-25 01:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('quanlycatruc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhvienkiptruc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phan_cong_kip_truc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DonViToChuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_don_vi', models.CharField(max_length=50, unique=True)),
                ('ten_don_vi', models.CharField(max_length=200)),
                ('loai_don_vi', models.CharField(choices=[('cong_ty', 'Công ty'), ('cum_nha_may', 'Cụm nhà máy'), ('nha_may', 'Nhà máy'), ('van_phong', 'Văn phòng'), ('khac', 'Khác')], default='nha_may', max_length=20)),
                ('thu_tu', models.PositiveSmallIntegerField(default=1)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
                ('don_vi_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='don_vi_con', to='quanlycatruc.donvitochuc')),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='don_vi_to_chuc', to='khovattu.bang_nha_may')),
            ],
            options={
                'verbose_name': 'Đơn vị tổ chức',
                'verbose_name_plural': 'Các đơn vị tổ chức',
                'ordering': ['thu_tu', 'ten_don_vi'],
            },
        ),
        migrations.CreateModel(
            name='BoPhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_bo_phan', models.CharField(max_length=50)),
                ('ten_bo_phan', models.CharField(max_length=150)),
                ('loai_bo_phan', models.CharField(choices=[('van_hanh', 'Vận hành'), ('ky_thuat', 'Kỹ thuật'), ('hanh_chinh', 'Hành chính'), ('bao_ve', 'Bảo vệ'), ('bao_tri', 'Bảo trì'), ('an_toan', 'An toàn'), ('khac', 'Khác')], default='khac', max_length=20)),
                ('thu_tu', models.PositiveSmallIntegerField(default=1)),
                ('dang_hoat_dong', models.BooleanField(default=True)),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bo_phan', to='quanlycatruc.donvitochuc')),
            ],
            options={
                'verbose_name': 'Bộ phận',
                'verbose_name_plural': 'Các bộ phận',
                'ordering': ['don_vi', 'thu_tu', 'ten_bo_phan'],
            },
        ),
        migrations.CreateModel(
            name='NhanSu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_nhan_vien', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ho_ten', models.CharField(max_length=150)),
                ('chuc_danh', models.CharField(blank=True, max_length=120)),
                ('dien_thoai', models.CharField(blank=True, max_length=30)),
                ('tu_ngay', models.DateField(default=datetime.date.today)),
                ('den_ngay', models.DateField(blank=True, null=True)),
                ('dang_lam_viec', models.BooleanField(default=True)),
                ('bo_phan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhan_su', to='quanlycatruc.bophan')),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhan_su', to='quanlycatruc.donvitochuc')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_su_ca_truc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân sự',
                'verbose_name_plural': 'Danh mục nhân sự',
                'ordering': ['don_vi', 'bo_phan', 'ho_ten'],
            },
        ),
        migrations.AddField(
            model_name='thanhvienkiptruc',
            name='nhan_su',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phan_cong_kip_truc', to='quanlycatruc.nhansu'),
        ),
        migrations.AddIndex(
            model_name='thanhvienkiptruc',
            index=models.Index(fields=['nhan_su', 'tu_ngay', 'den_ngay'], name='quanlycatru_nhan_su_6062f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='thanhvienkiptruc',
            constraint=models.CheckConstraint(condition=models.Q(('nhan_su__isnull', False), ('user__isnull', False), _connector='OR'), name='ck_thanhvien_co_nhansu_hoac_user'),
        ),
        migrations.AddConstraint(
            model_name='bophan',
            constraint=models.UniqueConstraint(fields=('don_vi', 'ma_bo_phan'), name='uq_bophan_donvi_ma'),
        ),
        migrations.AddIndex(
            model_name='nhansu',
            index=models.Index(fields=['don_vi', 'bo_phan', 'dang_lam_viec'], name='quanlycatru_don_vi__2e1cc8_idx'),
        ),
    ]
