# Generated by Django 5.2.17 on 2026-08-25 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlycatruc', '0003_migrate_existing_roster_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieuChinhNhanSuCaTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loai_ca', models.CharField(choices=[('ca_ngay', 'Ca ngày (08:00–20:00)'), ('ca_dem', 'Ca đêm (20:00–08:00)'), ('hanh_chinh', 'Ca kỹ thuật - hành chính')], max_length=20)),
                ('loai_dieu_chinh', models.CharField(choices=[('doi_ca', 'Đổi ca'), ('truc_thay', 'Trực thay'), ('nghi_phep', 'Nghỉ phép'), ('dieu_dong', 'Điều động')], max_length=20)),
                ('vai_tro_thay', models.CharField(blank=True, choices=[('truong_ca', 'Trưởng ca'), ('truc_chinh', 'Trực chính'), ('truc_phu', 'Trực phụ'), ('ky_thuat_vien', 'Kỹ thuật viên'), ('nhan_vien', 'Nhân viên')], max_length=20)),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(choices=[('du_thao', 'Dự thảo'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối'), ('da_huy', 'Đã hủy')], default='du_thao', max_length=20)),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True)),
                ('ly_do_tu_choi', models.TextField(blank=True)),
                ('ngay_truc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieu_chinh_nhan_su', to='quanlycatruc.ngaytrucca')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dieu_chinh_ca_da_duyet', to=settings.AUTH_USER_MODEL)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dieu_chinh_ca_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nhan_su_thay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cac_ca_truc_thay', to='quanlycatruc.nhansu')),
                ('nhan_su_vang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cac_ca_vang', to='quanlycatruc.nhansu')),
            ],
            options={
                'verbose_name': 'Điều chỉnh nhân sự ca trực',
                'verbose_name_plural': 'Điều chỉnh nhân sự ca trực',
                'ordering': ['ngay_truc__ngay', 'loai_ca', 'created_at'],
                'indexes': [models.Index(fields=['ngay_truc', 'loai_ca', 'trang_thai'], name='quanlycatru_ngay_tr_a94ea2_idx'), models.Index(fields=['nhan_su_thay', 'trang_thai'], name='quanlycatru_nhan_su_ad697e_idx')],
            },
        ),
    ]
