# Generated by Django 5.2.17 on 2026-08-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlycatruc', '0004_dieuchinhnhansucatruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieuchinhnhansucatruc',
            name='loai_ca_doi',
            field=models.CharField(blank=True, choices=[('ca_ngay', 'Ca ngày (08:00–20:00)'), ('ca_dem', 'Ca đêm (20:00–08:00)'), ('hanh_chinh', 'Ca kỹ thuật - hành chính')], max_length=20),
        ),
        migrations.AddField(
            model_name='dieuchinhnhansucatruc',
            name='ngay_truc_doi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dieu_chinh_doi_den', to='quanlycatruc.ngaytrucca'),
        ),
        migrations.AddField(
            model_name='dieuchinhnhansucatruc',
            name='vai_tro_doi',
            field=models.CharField(blank=True, choices=[('truong_ca', 'Trưởng ca'), ('truc_chinh', 'Trực chính'), ('truc_phu', 'Trực phụ'), ('ky_thuat_vien', 'Kỹ thuật viên'), ('nhan_vien', 'Nhân viên')], max_length=20),
        ),
    ]
