# Generated by Django 5.2.17 on 2026-08-25 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlycatruc', '0005_dieuchinhnhansucatruc_loai_ca_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieuchinhnhansucatruc',
            name='ma_phieu',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
