# Generated by Django 5.2.17 on 2026-08-25 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('quanlycatruc', '0008_align_admin_cycle_transition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhuongAnPhanCongCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thang', models.PositiveSmallIntegerField()),
                ('nam', models.PositiveIntegerField()),
                ('phien_ban', models.PositiveIntegerField(default=1)),
                ('ngay_hieu_luc', models.DateField()),
                ('trang_thai', models.CharField(choices=[('du_thao', 'Dự thảo'), ('da_ap_dung', 'Đã áp dụng'), ('da_khoa', 'Đã khóa')], default='du_thao', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_ap_dung', models.DateTimeField(blank=True, null=True)),
                ('nguoi_ap_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phuong_an_phan_cong_da_ap_dung', to=settings.AUTH_USER_MODEL)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phuong_an_phan_cong_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phuong_an_phan_cong_ca', to='khovattu.bang_nha_may')),
            ],
            options={
                'verbose_name': 'Phương án phân công ca',
                'verbose_name_plural': 'Phương án phân công ca',
                'ordering': ['-nam', '-thang', '-phien_ban'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhuongAnPhanCongCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vai_tro', models.CharField(blank=True, choices=[('truong_ca', 'Trưởng ca'), ('truc_chinh', 'Trực chính'), ('truc_phu', 'Trực phụ'), ('ky_thuat_vien', 'Kỹ thuật viên'), ('nhan_vien', 'Nhân viên')], max_length=20)),
                ('thu_tu_hien_thi', models.PositiveSmallIntegerField(default=1)),
                ('kip_truc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cac_phuong_an_phan_cong', to='quanlycatruc.kiptruc')),
                ('nhan_su', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_phuong_an_phan_cong', to='quanlycatruc.nhansu')),
                ('phuong_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanlycatruc.phuonganphancongca')),
            ],
            options={
                'verbose_name': 'Chi tiết phương án phân công',
                'verbose_name_plural': 'Chi tiết phương án phân công',
                'ordering': ['kip_truc__thu_tu', 'thu_tu_hien_thi', 'nhan_su__ho_ten'],
            },
        ),
        migrations.AddConstraint(
            model_name='phuonganphancongca',
            constraint=models.UniqueConstraint(fields=('nha_may', 'nam', 'thang', 'phien_ban'), name='uq_phuongan_phancong_ky_phienban'),
        ),
        migrations.AddConstraint(
            model_name='phuonganphancongca',
            constraint=models.CheckConstraint(condition=models.Q(('thang__gte', 1), ('thang__lte', 12)), name='ck_phuongan_thang'),
        ),
        migrations.AddConstraint(
            model_name='chitietphuonganphancongca',
            constraint=models.UniqueConstraint(fields=('phuong_an', 'nhan_su'), name='uq_phuongan_nhansu'),
        ),
    ]
