# Generated by Django 5.2.17 on 2026-08-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlycatruc', '0017_schedule_custom_cycles'),
        ('tochuc', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.AlterField(
            model_name='donvitochuc',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='don_vi_to_chuc', to='tochuc.nhamay'),
        ),
            migrations.AlterField(
            model_name='kiptruc',
            name='nha_may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_kip_truc', to='tochuc.nhamay'),
        ),
            migrations.AlterField(
            model_name='lichtrucca',
            name='nha_may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_truc_ca', to='tochuc.nhamay'),
        ),
            migrations.AlterField(
            model_name='mauchukycatruc',
            name='nha_may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_chu_ky_ca_truc', to='tochuc.nhamay'),
        ),
            migrations.AlterField(
            model_name='nhomlichtruc',
            name='nha_may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhom_lich_truc', to='tochuc.nhamay'),
        ),
            migrations.AlterField(
            model_name='phuonganphancongca',
            name='nha_may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phuong_an_phan_cong_ca', to='tochuc.nhamay'),
            )],
        ),
    ]
