# Generated by Django 5.1 on 2026-05-25 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'Nguoi dung'), ('assistant', 'Tro ly')], max_length=20)),
                ('content', models.TextField()),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('tools_called', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhan tro ly AI',
                'verbose_name_plural': 'Tin nhan tro ly AI',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['user', 'session_id', 'created_at'], name='ai_tools_ai_user_id_d0ff69_idx')],
            },
        ),
    ]
