# Generated by Django 5.1 on 2026-04-19 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatKySuKien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian_xay_ra', models.DateTimeField()),
                ('ten_he_thong_thiet_bi', models.CharField(max_length=255)),
                ('hien_tuong_dien_bien', models.TextField()),
                ('phan_tich_nguyen_nhan', models.TextField(blank=True)),
                ('qua_trinh_kiem_tra', models.TextField(blank=True)),
                ('qua_trinh_xu_ly', models.TextField(blank=True)),
                ('de_xuat_khac_phuc', models.TextField(blank=True)),
                ('bao_cho', models.CharField(blank=True, max_length=255)),
                ('thoi_gian_xu_ly', models.DateTimeField(blank=True, null=True)),
                ('ket_qua_kiem_tra_nguyen_nhan', models.TextField(blank=True)),
                ('noi_dung_xu_ly_khac_phuc', models.TextField(blank=True)),
                ('de_xuat_lien_quan', models.TextField(blank=True)),
                ('ket_qua_sau_xu_ly', models.TextField(blank=True)),
                ('hinh_anh_truoc_su_co', models.ImageField(blank=True, null=True, upload_to='operations/nhat_ky_su_kien/truoc_su_co/')),
                ('hinh_anh_sau_xu_ly', models.ImageField(blank=True, null=True, upload_to='operations/nhat_ky_su_kien/sau_xu_ly/')),
                ('trang_thai', models.CharField(choices=[('chua_xu_ly_xong', 'Chua xu ly xong'), ('xu_ly_xong', 'Xu ly xong')], default='chua_xu_ly_xong', max_length=32)),
                ('ben_ghi_nhan_su_kien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhat_ky_su_kien_da_ghi_nhan', to=settings.AUTH_USER_MODEL)),
                ('ben_xu_ly_su_kien_thiet_bi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhat_ky_su_kien_da_xu_ly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhat ky su kien',
                'verbose_name_plural': 'Nhat ky su kien',
                'ordering': ['-thoi_gian_xay_ra', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SogiaonhancaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay_truc', models.DateField()),
                ('ca_truc', models.CharField(choices=[('A', 'Ca A'), ('B', 'Ca B'), ('C', 'Ca C'), ('D', 'Ca D'), ('E', 'Ca E')], max_length=1)),
                ('dia_diem', models.CharField(blank=True, max_length=255)),
                ('truc_chinh', models.CharField(blank=True, max_length=255)),
                ('truc_phu', models.CharField(blank=True, max_length=255)),
                ('truc_ktvh', models.CharField(blank=True, max_length=255)),
                ('dieu_do_a0', models.CharField(blank=True, max_length=255)),
                ('dieu_do_a3', models.CharField(blank=True, max_length=255)),
                ('dieu_do_b3', models.CharField(blank=True, max_length=255)),
                ('thoi_gian_giao_ca', models.DateTimeField()),
                ('noi_dung_chi_tiet', models.TextField(blank=True)),
                ('tinh_trang_he_thong_truoc_ca', models.TextField(blank=True)),
                ('tinh_trang_van_hanh_trong_ca', models.TextField(blank=True)),
                ('cac_phuong_tien_trang_bi_ca', models.TextField(blank=True)),
                ('luu_y', models.TextField(blank=True)),
                ('tong_muc_luc', models.TextField(blank=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='operations/so_giao_nhan_ca_vh/')),
                ('giao_ca_ky_at', models.DateTimeField(blank=True, null=True)),
                ('nhan_ca_ky_at', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Cho xac nhan'), ('hoan_thanh', 'Hoan thanh')], default='cho_xac_nhan', max_length=20)),
                ('user_giao_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_vh_da_giao', to=settings.AUTH_USER_MODEL)),
                ('user_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_vh_da_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'So giao nhan ca van hanh',
                'verbose_name_plural': 'So giao nhan ca van hanh',
                'ordering': ['-ngay_truc', '-thoi_gian_giao_ca', '-created_at'],
            },
        ),
    ]
