# Generated by Django 5.1 on 2026-04-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhatkysukien',
            options={'ordering': ['-thoi_gian_xay_ra', '-created_at'], 'verbose_name': 'Nhật ký sự kiện', 'verbose_name_plural': 'Nhật ký sự kiện'},
        ),
        migrations.AlterModelOptions(
            name='sogiaonhancavh',
            options={'ordering': ['-ngay_truc', '-thoi_gian_giao_ca', '-created_at'], 'verbose_name': 'Sổ giao nhận ca vận hành', 'verbose_name_plural': 'Sổ giao nhận ca vận hành'},
        ),
        migrations.AddField(
            model_name='nhatkysukien',
            name='chu_ky_ben_ghi_nhan_su_kien',
            field=models.ImageField(blank=True, null=True, upload_to='operations/nhat_ky_su_kien/chu_ky/ghi_nhan/'),
        ),
        migrations.AddField(
            model_name='nhatkysukien',
            name='chu_ky_ben_xu_ly_su_kien_thiet_bi',
            field=models.ImageField(blank=True, null=True, upload_to='operations/nhat_ky_su_kien/chu_ky/xu_ly/'),
        ),
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='chu_ky_user_giao_ca',
            field=models.ImageField(blank=True, null=True, upload_to='operations/so_giao_nhan_ca_vh/chu_ky/giao_ca/'),
        ),
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='chu_ky_user_nhan_ca',
            field=models.ImageField(blank=True, null=True, upload_to='operations/so_giao_nhan_ca_vh/chu_ky/nhan_ca/'),
        ),
    ]
