# Generated by Django 5.1 on 2026-04-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0008_split_sukien_and_khacphucsukien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sogiaonhancavh',
            options={'ordering': ['-ngay_truc', '-thoi_gian_giao_ca', '-created_at'], 'verbose_name': 'Sá»• giao nháº\xadn ca váº\xadn hÃ\xa0nh', 'verbose_name_plural': 'Sá»• giao nháº\xadn ca váº\xadn hÃ\xa0nh'},
        ),
    ]
