# Generated by Django 5.1 on 2026-04-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0009_alter_sogiaonhancavh_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sogiaonhancavh',
            options={'ordering': ['-ngay_truc', '-thoi_gian_giao_ca', '-created_at'], 'verbose_name': 'Sổ giao nhận ca vận hành', 'verbose_name_plural': 'Sổ giao nhận ca vận hành'},
        ),
        migrations.RemoveField(
            model_name='khacphucsukien',
            name='chu_ky_nguoi_xac_nhan_lan_cuoi',
        ),
        migrations.RemoveField(
            model_name='khacphucsukien',
            name='nguoi_xac_nhan_lan_cuoi',
        ),
    ]
