# Generated by Django 5.1 on 2026-04-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0010_alter_sogiaonhancavh_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khacphucsukien',
            name='lich_su_xu_ly_tiep_tuc',
        ),
    ]
