# Generated by Django 5.1 on 2026-04-27 01:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_nguoi_tao_va_noi_dung_chi_tiet(apps, schema_editor):
    SogiaonhancaVH = apps.get_model("nhatkyvanhanh", "SogiaonhancaVH")
    ChiTietSoGiaoNhanCaVH = apps.get_model("nhatkyvanhanh", "ChiTietSoGiaoNhanCaVH")

    for so in SogiaonhancaVH.objects.all().iterator():
        nguoi_tao_id = so.nguoi_tao_id or so.user_giao_ca_id
        if not so.nguoi_tao_id and nguoi_tao_id:
            so.nguoi_tao_id = nguoi_tao_id
            so.save(update_fields=["nguoi_tao"])

        noi_dung = (so.noi_dung_chi_tiet or "").strip()
        if noi_dung and not ChiTietSoGiaoNhanCaVH.objects.filter(so_giao_nhan_ca_id=so.id).exists():
            ChiTietSoGiaoNhanCaVH.objects.create(
                so_giao_nhan_ca_id=so.id,
                thoi_gian=so.thoi_gian_giao_ca,
                tieu_de="Noi dung chi tiet",
                noi_dung=noi_dung,
                thu_tu=1,
                nguoi_tao_id=nguoi_tao_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0016_dienbiensukien_chuc_danh_nguoi_tao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_vh_da_tao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sogiaonhancavh',
            name='user_nhan_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_vh_da_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChiTietSoGiaoNhanCaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('tieu_de', models.CharField(blank=True, max_length=255)),
                ('noi_dung', models.TextField()),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_so_giao_nhan_ca_vh_da_tao', to=settings.AUTH_USER_MODEL)),
                ('so_giao_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noi_dung_chi_tiets', to='nhatkyvanhanh.sogiaonhancavh')),
            ],
            options={
                'verbose_name': 'Nội dung chi tiết sổ giao nhận ca vận hành',
                'verbose_name_plural': 'Nội dung chi tiết sổ giao nhận ca vận hành',
                'ordering': ['thu_tu', 'thoi_gian', 'created_at'],
            },
        ),
        migrations.RunPython(
            backfill_nguoi_tao_va_noi_dung_chi_tiet,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='sogiaonhancavh',
            name='tinh_trang_he_thong_truoc_ca',
        ),
    ]
