# Generated by Django 5.1 on 2026-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0019_drop_user_nhan_ca_not_null_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sogiaonhancavh',
            options={'ordering': ['-ngay_truc', '-thoi_gian_bat_dau_ca', '-thoi_gian_giao_ca', '-created_at'], 'verbose_name': 'Sổ giao nhận ca vận hành', 'verbose_name_plural': 'Sổ giao nhận ca vận hành'},
        ),
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='thoi_gian_bat_dau_ca',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
