# Generated by Django 5.1 on 2026-04-27 07:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0021_clear_premature_shift_log_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SogiaonhancaHC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay_truc', models.DateField()),
                ('dia_diem', models.CharField(blank=True, max_length=255)),
                ('nguoi_truc', models.CharField(blank=True, max_length=255)),
                ('nguoi_truc_2', models.CharField(blank=True, max_length=255)),
                ('nguoi_truc_3', models.CharField(blank=True, max_length=255)),
                ('thoi_gian_bat_dau_ca', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_giao_ca', models.DateTimeField()),
                ('luu_y', models.TextField(blank=True)),
                ('chu_ky_user_giao_ca', models.ImageField(blank=True, null=True, upload_to='operations/so_giao_nhan_ca_hc/chu_ky/giao_ca/')),
                ('chu_ky_user_nhan_ca', models.ImageField(blank=True, null=True, upload_to='operations/so_giao_nhan_ca_hc/chu_ky/nhan_ca/')),
                ('giao_ca_ky_at', models.DateTimeField(blank=True, null=True)),
                ('nhan_ca_ky_at', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Cho xac nhan'), ('hoan_thanh', 'Hoan thanh')], default='cho_xac_nhan', max_length=20)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_hc_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_hc', to='khovattu.bang_nha_may', verbose_name='Nha may')),
                ('user_giao_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_hc_da_giao', to=settings.AUTH_USER_MODEL)),
                ('user_nhan_ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_hc_da_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'So giao nhan ca hanh chinh',
                'verbose_name_plural': 'So giao nhan ca hanh chinh',
                'ordering': ['-ngay_truc', '-thoi_gian_bat_dau_ca', '-thoi_gian_giao_ca', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietSoGiaoNhanCaHC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('tieu_de', models.CharField(blank=True, max_length=255)),
                ('noi_dung', models.TextField()),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_so_giao_nhan_ca_hc_da_tao', to=settings.AUTH_USER_MODEL)),
                ('so_giao_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noi_dung_chi_tiets', to='nhatkyvanhanh.sogiaonhancahc')),
            ],
            options={
                'verbose_name': 'Noi dung chi tiet so giao nhan ca hanh chinh',
                'verbose_name_plural': 'Noi dung chi tiet so giao nhan ca hanh chinh',
                'ordering': ['thu_tu', 'thoi_gian', 'created_at'],
            },
        ),
    ]
