# Generated by Django 5.1 on 2026-04-27 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0022_sogiaonhancahc_chitietsogiaonhancahc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiTrucSoGiaoNhanCaHC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('ten_nguoi_truc', models.CharField(max_length=255)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nguoi_truc_so_giao_nhan_ca_hc_da_tao', to=settings.AUTH_USER_MODEL)),
                ('so_giao_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_truc_chi_tiets', to='nhatkyvanhanh.sogiaonhancahc')),
            ],
            options={
                'verbose_name': 'Nguoi truc so giao nhan ca hanh chinh',
                'verbose_name_plural': 'Nguoi truc so giao nhan ca hanh chinh',
                'ordering': ['thu_tu', 'thoi_gian', 'created_at'],
            },
        ),
    ]
