# Generated by Django 5.1 on 2026-04-28 07:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0023_nguoitrucsogiaonhancahc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonhatkyvanhanh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('noi_dung_tao', models.TextField()),
                ('chu_ky_nguoi_tao', models.ImageField(blank=True, null=True, upload_to='operations/so_nhat_ky_van_hanh/chu_ky/nguoi_tao/')),
                ('chu_ky_nguoi_xac_nhan', models.ImageField(blank=True, null=True, upload_to='operations/so_nhat_ky_van_hanh/chu_ky/nguoi_xac_nhan/')),
                ('xac_nhan_at', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Cho xac nhan'), ('hoan_thanh', 'Hoan thanh')], default='cho_xac_nhan', max_length=20)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nguoi_xac_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh_da_xac_nhan', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh', to='khovattu.bang_nha_may', verbose_name='Nha may')),
            ],
            options={
                'verbose_name': 'So nhat ky van hanh',
                'verbose_name_plural': 'So nhat ky van hanh',
                'ordering': ['-thoi_gian_tao', '-created_at'],
            },
        ),
    ]
