# Generated by Django 5.1 on 2026-04-29 02:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0024_sonhatkyvanhanh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SonhatkyvanhanhDiesel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('noi_dung', models.TextField(blank=True)),
                ('i', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='I (A)')),
                ('u', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='U (V)')),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='F (Hz)')),
                ('i_sac', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='I sac (A)')),
                ('u_sac', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='U sac (V)')),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P (KW)')),
                ('q', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Q (KVAr)')),
                ('chi_so_gio_vh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('t_may', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='T may (C)')),
                ('muc_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Muc dau (lit)')),
                ('ap_luc_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ca_truc', models.CharField(blank=True, max_length=50)),
                ('chu_ky_nguoi_tao', models.ImageField(blank=True, null=True, upload_to='operations/so_nhat_ky_van_hanh_diesel/chu_ky/nguoi_tao/')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh_diesel_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh_diesel', to='khovattu.bang_nha_may', verbose_name='Nha may')),
            ],
            options={
                'verbose_name': 'So nhat ky van hanh Diesel',
                'verbose_name_plural': 'So nhat ky van hanh Diesel',
                'ordering': ['-thoi_gian', '-created_at'],
            },
        ),
    ]
