# Generated by Django 5.1 on 2026-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0025_sonhatkyvanhanhdiesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukien',
            name='chi_dao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sukien',
            name='qua_trinh_xu_ly',
            field=models.TextField(blank=True),
        ),
    ]
