# Generated by Django 5.1 on 2026-05-06 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0026_sukien_chi_dao_sukien_qua_trinh_xu_ly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sukien',
            name='chu_ky_nguoi_chi_dao',
            field=models.ImageField(blank=True, null=True, upload_to='operations/nhat_ky_su_kien/chu_ky/chi_dao/'),
        ),
        migrations.AddField(
            model_name='sukien',
            name='nguoi_chi_dao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_kien_da_chi_dao', to=settings.AUTH_USER_MODEL),
        ),
    ]
