# Generated by Django 5.1 on 2026-05-10 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0028_sukien_loai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoBCHCSongHinh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay_dong_bo', models.DateField(unique=True)),
                ('muc_nuoc_quy_trinh', models.CharField(blank=True, max_length=50)),
                ('muc_nuoc_quy_trinh_tu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('muc_nuoc_quy_trinh_den', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('muc_nuoc_ho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luu_luong_ve_ho', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('luu_luong_xa_tran', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('luu_luong_chay_may', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('luu_luong_chay_may_qt', models.CharField(blank=True, max_length=50)),
                ('nguyen_nhan_khong_dap_ung', models.TextField(blank=True)),
                ('chu_ky_nguoi_dong_bo', models.ImageField(blank=True, null=True, upload_to='operations/so_bchc_song_hinh/chu_ky/nguoi_dong_bo/')),
                ('nguoi_dong_bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_bchc_song_hinh_da_dong_bo', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_bchc_song_hinh', to='khovattu.bang_nha_may', verbose_name='Nha may')),
            ],
            options={
                'verbose_name': 'So BCHC Song Hinh',
                'verbose_name_plural': 'So BCHC Song Hinh',
                'ordering': ['-ngay_dong_bo', '-created_at'],
            },
        ),
    ]
