# Generated by Django 5.1 on 2026-05-13 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0029_sobchcsonghinh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoAnToanDauGio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay_dong_bo', models.DateField(unique=True)),
                ('tinh_trang_an_toan', models.CharField(blank=True, max_length=255)),
                ('chu_ky_nguoi_dong_bo', models.ImageField(blank=True, null=True, upload_to='operations/so_an_toan_dau_gio/chu_ky/nguoi_dong_bo/')),
                ('nguoi_dong_bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_an_toan_dau_gio_da_dong_bo', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_an_toan_dau_gio', to='khovattu.bang_nha_may', verbose_name='Nha may')),
            ],
            options={
                'verbose_name': 'So An Toan Dau Gio',
                'verbose_name_plural': 'So An Toan Dau Gio',
                'ordering': ['-ngay_dong_bo', '-created_at'],
            },
        ),
    ]
