# Generated by Django 5.1 on 2026-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0030_soantoandaugio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soantoandaugio',
            options={'ordering': ['-ngay_dong_bo', '-ca_truc', '-created_at'], 'verbose_name': 'So An Toan Dau Gio', 'verbose_name_plural': 'So An Toan Dau Gio'},
        ),
        migrations.AddField(
            model_name='soantoandaugio',
            name='ca_truc',
            field=models.CharField(choices=[('ca_ngay', 'Ca ngày'), ('ca_dem', 'Ca đêm')], default='ca_ngay', max_length=10),
        ),
        migrations.AlterField(
            model_name='soantoandaugio',
            name='ngay_dong_bo',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='soantoandaugio',
            unique_together={('ngay_dong_bo', 'ca_truc')},
        ),
    ]
