# Generated by Django 5.1 on 2026-05-14 07:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0031_alter_soantoandaugio_options_soantoandaugio_ca_truc_and_more'),
        ('quanlyvanhanh', '0020_convert_thoi_diem_nhap_to_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoChuyenDoiThietBiTuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuan_bat_dau', models.DateField()),
                ('tuan_ket_thuc', models.DateField()),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_thiet_bi_tuan_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_thiet_bi_tuan', to='khovattu.bang_nha_may', verbose_name='Nha may')),
            ],
            options={
                'verbose_name': 'So chuyen doi thiet bi tuan',
                'verbose_name_plural': 'So chuyen doi thiet bi tuan',
                'ordering': ['-tuan_bat_dau', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanChuyenDoiThietBi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu_chung', models.TextField(blank=True)),
                ('nguoi_thuc_hien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lan_chuyen_doi_thiet_bi_da_thuc_hien', to=settings.AUTH_USER_MODEL)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lan_chuyen_dois', to='nhatkyvanhanh.sochuyendoithietbituan')),
            ],
            options={
                'verbose_name': 'Lan chuyen doi thiet bi',
                'verbose_name_plural': 'Lan chuyen doi thiet bi',
                'ordering': ['thoi_gian', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietChuyenDoiThietBi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_may', models.CharField(choices=[('H1', 'To may H1'), ('H2', 'To may H2'), ('tu_dung', 'Tu dung')], max_length=20)),
                ('nhom_thiet_bi', models.CharField(blank=True, max_length=255)),
                ('trang_thai', models.CharField(blank=True, choices=[('lam_viec', 'Lam viec'), ('du_phong', 'Du phong')], max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_chuyen_doi_thiet_bi', to='quanlyvanhanh.thietbi')),
                ('lan_chuyen_doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='nhatkyvanhanh.lanchuyendoithietbi')),
            ],
            options={
                'verbose_name': 'Chi tiet chuyen doi thiet bi',
                'verbose_name_plural': 'Chi tiet chuyen doi thiet bi',
                'ordering': ['to_may', 'thu_tu', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('lan_chuyen_doi', 'thiet_bi'), name='uq_chi_tiet_chuyen_doi_lan_thiet_bi')],
            },
        ),
        migrations.CreateModel(
            name='MauChuyenDoiThietBi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_may', models.CharField(choices=[('H1', 'To may H1'), ('H2', 'To may H2'), ('tu_dung', 'Tu dung')], max_length=20)),
                ('nhom_thiet_bi', models.CharField(blank=True, max_length=255)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('dang_su_dung', models.BooleanField(default=True)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_thiet_bi', to='khovattu.bang_nha_may', verbose_name='Nha may')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_thiet_bi', to='quanlyvanhanh.thietbi')),
            ],
            options={
                'verbose_name': 'Mau chuyen doi thiet bi',
                'verbose_name_plural': 'Mau chuyen doi thiet bi',
                'ordering': ['nha_may', 'to_may', 'thu_tu', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('nha_may', 'thiet_bi'), name='uq_mau_chuyen_doi_thiet_bi_nha_may_thiet_bi')],
            },
        ),
        migrations.AddConstraint(
            model_name='sochuyendoithietbituan',
            constraint=models.UniqueConstraint(fields=('nha_may', 'tuan_bat_dau'), name='uq_so_chuyen_doi_thiet_bi_tuan_nha_may_tuan'),
        ),
    ]
