# Generated by Django 5.1 on 2026-05-14 07:56

import nhatkyvanhanh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0032_sochuyendoithietbituan_lanchuyendoithietbi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sochuyendoithietbituan',
            options={'ordering': ['-nam', '-tuan', '-created_at'], 'verbose_name': 'So chuyen doi thiet bi tuan', 'verbose_name_plural': 'So chuyen doi thiet bi tuan'},
        ),
        migrations.RemoveConstraint(
            model_name='sochuyendoithietbituan',
            name='uq_so_chuyen_doi_thiet_bi_tuan_nha_may_tuan',
        ),
        migrations.AddField(
            model_name='sochuyendoithietbituan',
            name='nam',
            field=models.PositiveSmallIntegerField(default=nhatkyvanhanh.models._current_year),
        ),
        migrations.AddField(
            model_name='sochuyendoithietbituan',
            name='tuan',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='sochuyendoithietbituan',
            constraint=models.UniqueConstraint(fields=('nha_may', 'nam', 'tuan'), name='uq_so_chuyen_doi_thiet_bi_tuan_nha_may_nam_tuan'),
        ),
    ]
