# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhatkyvanhanh", "0033_alter_sochuyendoithietbituan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sochuyendoithietbituan",
            name="ca_truc",
            field=models.CharField(
                choices=[("A", "Ca A"), ("B", "Ca B"), ("C", "Ca C"), ("D", "Ca D")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="sochuyendoithietbituan",
            name="uq_so_chuyen_doi_thiet_bi_tuan_nha_may_nam_tuan",
        ),
        migrations.AddConstraint(
            model_name="sochuyendoithietbituan",
            constraint=models.UniqueConstraint(
                fields=("nha_may", "nam", "tuan", "ca_truc"),
                name="uq_so_chuyen_doi_thiet_bi_tuan_nha_may_nam_tuan_ca",
            ),
        ),
    ]
