# Generated by Django 5.1 on 2026-05-24 09:38

import django.db.models.deletion
import nhatkyvanhanh.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0035_sukien_thiet_bi'),
        ('quanlyvanhanh', '0020_convert_thoi_diem_nhap_to_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoChuyenDoiTBThang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nam', models.PositiveSmallIntegerField(default=nhatkyvanhanh.models._current_year)),
                ('thang', models.PositiveSmallIntegerField(default=1)),
                ('ca_truc', models.CharField(choices=[('A', 'Ca A'), ('B', 'Ca B'), ('C', 'Ca C'), ('D', 'Ca D')], default='A', max_length=1)),
                ('thang_bat_dau', models.DateField()),
                ('thang_ket_thuc', models.DateField()),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_tb_thang_da_tao', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_tb_thang', to='khovattu.bang_nha_may', verbose_name='Nha may')),
            ],
            options={
                'verbose_name': 'So chuyen doi TB thang',
                'verbose_name_plural': 'So chuyen doi TB thang',
                'ordering': ['-nam', '-thang', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietChuyenDoiTBThang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_nhom', models.CharField(blank=True, max_length=20)),
                ('ten_nhom', models.CharField(max_length=255)),
                ('don_vi_nhom', models.CharField(blank=True, max_length=50)),
                ('don_vi', models.CharField(default='Lan', max_length=50)),
                ('dau_thang', models.IntegerField(default=0)),
                ('cuoi_thang', models.IntegerField(default=0)),
                ('thuc_hien', models.IntegerField(default=0, editable=False)),
                ('ghi_chu', models.TextField(blank=True)),
                ('thu_tu_nhom', models.PositiveIntegerField(default=1)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_chuyen_doi_tb_thang', to='quanlyvanhanh.thietbi')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='nhatkyvanhanh.sochuyendoitbthang')),
            ],
            options={
                'verbose_name': 'Chi tiet chuyen doi TB thang',
                'verbose_name_plural': 'Chi tiet chuyen doi TB thang',
                'ordering': ['thu_tu_nhom', 'thu_tu', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MauChuyenDoiTBThang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_nhom', models.CharField(blank=True, max_length=20)),
                ('ten_nhom', models.CharField(max_length=255)),
                ('don_vi_nhom', models.CharField(blank=True, max_length=50)),
                ('don_vi', models.CharField(default='Lan', max_length=50)),
                ('thu_tu_nhom', models.PositiveIntegerField(default=1)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('dang_su_dung', models.BooleanField(default=True)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_tb_thang', to='khovattu.bang_nha_may', verbose_name='Nha may')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_tb_thang', to='quanlyvanhanh.thietbi')),
            ],
            options={
                'verbose_name': 'Mau chuyen doi TB thang',
                'verbose_name_plural': 'Mau chuyen doi TB thang',
                'ordering': ['nha_may', 'thu_tu_nhom', 'thu_tu', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('nha_may', 'thiet_bi'), name='uq_mau_chuyen_doi_tb_thang_nha_may_thiet_bi')],
            },
        ),
        migrations.AddConstraint(
            model_name='sochuyendoitbthang',
            constraint=models.UniqueConstraint(fields=('nha_may', 'nam', 'thang', 'ca_truc'), name='uq_so_chuyen_doi_tb_thang_nha_may_nam_thang_ca'),
        ),
        migrations.AddConstraint(
            model_name='chitietchuyendoitbthang',
            constraint=models.UniqueConstraint(fields=('so', 'thiet_bi'), name='uq_chi_tiet_chuyen_doi_tb_thang_so_thiet_bi'),
        ),
    ]
