# Generated by Django 5.1 on 2026-05-25 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0036_sochuyendoitbthang_chitietchuyendoitbthang_and_more'),
        ('quanlyvanhanh', '0020_convert_thoi_diem_nhap_to_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chitietchuyendoitbthang',
            options={'ordering': ['thu_tu_nhom', 'thu_tu', 'created_at'], 'verbose_name': 'Chi tiết chuyển đổi TB tháng', 'verbose_name_plural': 'Chi tiết chuyển đổi TB tháng'},
        ),
        migrations.AlterModelOptions(
            name='chitietchuyendoithietbi',
            options={'ordering': ['to_may', 'thu_tu', 'created_at'], 'verbose_name': 'Chi tiết chuyển đổi thiết bị', 'verbose_name_plural': 'Chi tiết chuyển đổi thiết bị'},
        ),
        migrations.AlterModelOptions(
            name='chitietsogiaonhancahc',
            options={'ordering': ['thu_tu', 'thoi_gian', 'created_at'], 'verbose_name': 'Nội dung chi tiết sổ giao nhận ca hành chính', 'verbose_name_plural': 'Nội dung chi tiết sổ giao nhận ca hành chính'},
        ),
        migrations.AlterModelOptions(
            name='dienbiensukien',
            options={'ordering': ['thoi_gian_dien_bien', 'created_at'], 'verbose_name': 'Diễn biến sự kiện', 'verbose_name_plural': 'Diễn biến sự kiện'},
        ),
        migrations.AlterModelOptions(
            name='khacphucsukien',
            options={'ordering': ['-thoi_gian_xu_ly', '-created_at'], 'verbose_name': 'Khắc phục sự kiện', 'verbose_name_plural': 'Khắc phục sự kiện'},
        ),
        migrations.AlterModelOptions(
            name='lanchuyendoithietbi',
            options={'ordering': ['thoi_gian', 'created_at'], 'verbose_name': 'Lần chuyển đổi thiết bị', 'verbose_name_plural': 'Lần chuyển đổi thiết bị'},
        ),
        migrations.AlterModelOptions(
            name='mauchuyendoitbthang',
            options={'ordering': ['nha_may', 'thu_tu_nhom', 'thu_tu', 'created_at'], 'verbose_name': 'Mẫu chuyển đổi TB tháng', 'verbose_name_plural': 'Mẫu chuyển đổi TB tháng'},
        ),
        migrations.AlterModelOptions(
            name='mauchuyendoithietbi',
            options={'ordering': ['nha_may', 'to_may', 'thu_tu', 'created_at'], 'verbose_name': 'Mẫu chuyển đổi thiết bị', 'verbose_name_plural': 'Mẫu chuyển đổi thiết bị'},
        ),
        migrations.AlterModelOptions(
            name='nguoitrucsogiaonhancahc',
            options={'ordering': ['thu_tu', 'thoi_gian', 'created_at'], 'verbose_name': 'Người trực sổ giao nhận ca hành chính', 'verbose_name_plural': 'Người trực sổ giao nhận ca hành chính'},
        ),
        migrations.AlterModelOptions(
            name='soantoandaugio',
            options={'ordering': ['-ngay_dong_bo', '-ca_truc', '-created_at'], 'verbose_name': 'Sổ an toàn đầu giờ', 'verbose_name_plural': 'Sổ an toàn đầu giờ'},
        ),
        migrations.AlterModelOptions(
            name='sobchcsonghinh',
            options={'ordering': ['-ngay_dong_bo', '-created_at'], 'verbose_name': 'Sổ BCHC Sông Hinh', 'verbose_name_plural': 'Sổ BCHC Sông Hinh'},
        ),
        migrations.AlterModelOptions(
            name='sochuyendoitbthang',
            options={'ordering': ['-nam', '-thang', '-created_at'], 'verbose_name': 'Sổ chuyển đổi TB tháng', 'verbose_name_plural': 'Sổ chuyển đổi TB tháng'},
        ),
        migrations.AlterModelOptions(
            name='sochuyendoithietbituan',
            options={'ordering': ['-nam', '-tuan', '-created_at'], 'verbose_name': 'Sổ chuyển đổi thiết bị tuần', 'verbose_name_plural': 'Sổ chuyển đổi thiết bị tuần'},
        ),
        migrations.AlterModelOptions(
            name='sogiaonhancahc',
            options={'ordering': ['-ngay_truc', '-thoi_gian_bat_dau_ca', '-thoi_gian_giao_ca', '-created_at'], 'verbose_name': 'Sổ giao nhận ca hành chính', 'verbose_name_plural': 'Sổ giao nhận ca hành chính'},
        ),
        migrations.AlterModelOptions(
            name='sonhatkyvanhanh',
            options={'ordering': ['-thoi_gian_tao', '-created_at'], 'verbose_name': 'Sổ nhật ký vận hành', 'verbose_name_plural': 'Sổ nhật ký vận hành'},
        ),
        migrations.AlterModelOptions(
            name='sonhatkyvanhanhdiesel',
            options={'ordering': ['-thoi_gian', '-created_at'], 'verbose_name': 'Sổ nhật ký vận hành Diesel', 'verbose_name_plural': 'Sổ nhật ký vận hành Diesel'},
        ),
        migrations.AlterModelOptions(
            name='sukien',
            options={'ordering': ['-thoi_gian_xay_ra', '-created_at'], 'verbose_name': 'Sự kiện', 'verbose_name_plural': 'Sự kiện'},
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='to_may',
            field=models.CharField(choices=[('H1', 'Tổ máy H1'), ('H2', 'Tổ máy H2'), ('tu_dung', 'Tự dùng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('lam_viec', 'Làm việc'), ('du_phong', 'Dự phòng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mauchuyendoitbthang',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_tb_thang', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_thiet_bi', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='to_may',
            field=models.CharField(choices=[('H1', 'Tổ máy H1'), ('H2', 'Tổ máy H2'), ('tu_dung', 'Tự dùng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='soantoandaugio',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_an_toan_dau_gio', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sobchcsonghinh',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_bchc_song_hinh', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sochuyendoitbthang',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_tb_thang', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_thiet_bi_tuan', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sogiaonhancahc',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_hc', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sogiaonhancahc',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('hoan_thanh', 'Hoàn thành')], default='cho_xac_nhan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sogiaonhancavh',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_vh', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sogiaonhancavh',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('hoan_thanh', 'Hoàn thành')], default='cho_xac_nhan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanh',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanh',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('hoan_thanh', 'Hoàn thành')], default='cho_xac_nhan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanhdiesel',
            name='i_sac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='I sạc (A)'),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanhdiesel',
            name='muc_dau',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mức dầu (lit)'),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanhdiesel',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh_diesel', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanhdiesel',
            name='t_may',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='T máy (C)'),
        ),
        migrations.AlterField(
            model_name='sonhatkyvanhanhdiesel',
            name='u_sac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='U sạc (V)'),
        ),
        migrations.AlterField(
            model_name='sukien',
            name='loai',
            field=models.CharField(choices=[('khiem_khuyet', 'Khiếm khuyết'), ('su_co', 'Sự cố')], default='su_co', max_length=32),
        ),
        migrations.AlterField(
            model_name='sukien',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_kiens', to='khovattu.bang_nha_may', verbose_name='Nhà máy'),
        ),
        migrations.AlterField(
            model_name='sukien',
            name='thiet_bi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_kiens', to='quanlyvanhanh.thietbi', verbose_name='Thiết bị liên quan'),
        ),
        migrations.AlterField(
            model_name='sukien',
            name='trang_thai',
            field=models.CharField(choices=[('chua_xu_ly_xong', 'Chưa xử lý xong'), ('dang_xu_ly', 'Đang xử lý'), ('xu_ly_xong', 'Xử lý xong')], default='chua_xu_ly_xong', max_length=32),
        ),
    ]
