# Generated by Django 5.1 on 2026-05-28 02:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0038_chidaosukien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuuYChiDaoSoGiaoNhanCaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('noi_dung', models.TextField()),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='luu_y_chi_dao_so_giao_nhan_ca_vh_da_tao', to=settings.AUTH_USER_MODEL)),
                ('so_giao_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luu_y_chi_daos', to='nhatkyvanhanh.sogiaonhancavh')),
            ],
            options={
                'verbose_name': 'Luu y chi dao so giao nhan ca van hanh',
                'verbose_name_plural': 'Luu y chi dao so giao nhan ca van hanh',
                'ordering': ['thoi_gian', 'created_at'],
            },
        ),
    ]
