# Generated by Django 5.1 on 2026-05-31 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0039_luuychidaosogiaonhancavh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soantoandaugio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sobchcsonghinh',
            name='ngay_dong_bo',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='soantoandaugio',
            constraint=models.UniqueConstraint(fields=('nha_may', 'ngay_dong_bo', 'ca_truc'), name='uq_soantoandaugio_nha_may_ngay_ca'),
        ),
        migrations.AddConstraint(
            model_name='sobchcsonghinh',
            constraint=models.UniqueConstraint(fields=('nha_may', 'ngay_dong_bo'), name='uq_sobchcsonghinh_nha_may_ngay'),
        ),
        migrations.AddConstraint(
            model_name='sogiaonhancahc',
            constraint=models.UniqueConstraint(fields=('nha_may', 'ngay_truc'), name='uq_sogiaonhancahc_nha_may_ngay'),
        ),
        migrations.AddConstraint(
            model_name='sogiaonhancavh',
            constraint=models.UniqueConstraint(fields=('nha_may', 'ngay_truc', 'ca_truc'), name='uq_sogiaonhancavh_nha_may_ngay_ca'),
        ),
    ]
