# Generated by Django 5.2.17 on 2026-08-22 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_shift_staff(apps, schema_editor):
    ShiftLog = apps.get_model('nhatkyvanhanh', 'SogiaonhancaVH')
    ShiftStaff = apps.get_model('nhatkyvanhanh', 'NhanSuSoGiaoNhanCaVH')

    for shift_log in ShiftLog.objects.all().iterator():
        order = 1
        primary = (shift_log.truc_chinh or '').strip()
        if primary:
            ShiftStaff.objects.create(
                so_giao_nhan_ca_id=shift_log.pk,
                vai_tro='truc_chinh',
                ten_nhan_su=primary,
                thu_tu=order,
                nguoi_tao_id=shift_log.nguoi_tao_id,
            )
            order += 1

        assistants = [
            name.strip()
            for name in (shift_log.truc_phu or '').split(',')
            if name.strip()
        ]
        for name in assistants:
            ShiftStaff.objects.create(
                so_giao_nhan_ca_id=shift_log.pk,
                vai_tro='truc_phu',
                ten_nhan_su=name,
                thu_tu=order,
                nguoi_tao_id=shift_log.nguoi_tao_id,
            )
            order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0040_tighten_permissions_and_factory_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanSuSoGiaoNhanCaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vai_tro', models.CharField(choices=[('truc_chinh', 'Trực chính'), ('truc_phu', 'Trực phụ')], max_length=20)),
                ('ten_nhan_su', models.CharField(max_length=255)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhan_su_so_giao_nhan_ca_vh_da_tao', to=settings.AUTH_USER_MODEL)),
                ('so_giao_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_su_ca', to='nhatkyvanhanh.sogiaonhancavh')),
            ],
            options={
                'verbose_name': 'Nhân sự sổ giao nhận ca vận hành',
                'verbose_name_plural': 'Nhân sự sổ giao nhận ca vận hành',
                'ordering': ['thu_tu', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vai_tro', 'truc_chinh')), fields=('so_giao_nhan_ca',), name='uq_sogiaonhancavh_mot_truc_chinh')],
            },
        ),
        migrations.RunPython(backfill_shift_staff, migrations.RunPython.noop),
    ]
