# Generated by Django 5.2.17 on 2026-08-23 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0043_alter_luuychidaosogiaonhancavh_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='trang_thai_thiet_bi',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách trạng thái thiết bị tại thời điểm giao nhận ca'),
        ),
        migrations.CreateModel(
            name='AnhSoGiaoNhanCaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hinh_anh', models.ImageField(upload_to='operations/so_giao_nhan_ca_vh/bo_sung/')),
                ('chu_thich', models.CharField(blank=True, max_length=255)),
                ('thu_tu', models.PositiveIntegerField(default=1)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anh_so_giao_nhan_ca_vh_da_tao', to=settings.AUTH_USER_MODEL)),
                ('so_giao_nhan_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh_bo_sung', to='nhatkyvanhanh.sogiaonhancavh')),
            ],
            options={
                'verbose_name': 'Ảnh sổ giao nhận ca vận hành',
                'verbose_name_plural': 'Ảnh sổ giao nhận ca vận hành',
                'ordering': ['thu_tu', 'created_at'],
            },
        ),
    ]
