# Generated by Django 5.2.17 on 2026-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0044_sogiaonhancavh_trang_thai_thiet_bi_anhsogiaonhancavh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sogiaonhancavh',
            name='ca_truc',
            field=models.CharField(choices=[('ngay', 'Ca ngày (08:00–20:00)'), ('dem', 'Ca đêm (20:00–08:00 hôm sau)'), ('sang', 'Ca sáng (08:00–12:00)'), ('chieu', 'Ca chiều (12:00–20:00)'), ('A', 'Ca A'), ('B', 'Ca B'), ('C', 'Ca C'), ('D', 'Ca D'), ('E', 'Ca E')], max_length=16),
        ),
    ]
