# Generated by Django 5.2.17 on 2026-08-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0045_alter_sogiaonhancavh_ca_truc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='loai_thoi_gian_truc',
            field=models.CharField(choices=[('ngay', 'Ca ngày (08:00–20:00)'), ('dem', 'Ca đêm (20:00–08:00 hôm sau)'), ('sang', 'Ca sáng (08:00–12:00)'), ('chieu', 'Ca chiều (12:00–20:00)')], default='ngay', max_length=16, verbose_name='Loại thời gian trực'),
        ),
        migrations.AlterField(
            model_name='sogiaonhancavh',
            name='ca_truc',
            field=models.CharField(choices=[('A', 'Ca A'), ('B', 'Ca B'), ('C', 'Ca C'), ('D', 'Ca D'), ('E', 'Ca E')], max_length=1),
        ),
    ]
