# Generated by Django 5.2.17 on 2026-08-28 10:55

import django.db.models.deletion
import nhatkyvanhanh.models.base
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0051_nguoitrucsogiaonhancahc_time_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BangPhanCongNhiemVuHC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thang', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('nam', models.PositiveSmallIntegerField(default=nhatkyvanhanh.models.base._current_year, verbose_name='Năm')),
                ('tieu_de', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề')),
                ('ngay_lap', models.DateField(blank=True, null=True, verbose_name='Ngày lập')),
                ('dia_diem_lap', models.CharField(blank=True, max_length=255, verbose_name='Địa điểm lập')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú / Hướng dẫn')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bang_phan_cong_nhiem_vu_hc_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bang_phan_cong_nhiem_vu_hc', to='khovattu.bang_nha_may', verbose_name='Nhà máy')),
            ],
            options={
                'verbose_name': 'Bảng phân công nhiệm vụ ca HC',
                'verbose_name_plural': 'Bảng phân công nhiệm vụ ca HC',
                'ordering': ['-nam', '-thang', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhiemVuThuTrongTuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stt', models.PositiveSmallIntegerField(default=1, verbose_name='STT')),
                ('thu', models.CharField(max_length=20, verbose_name='Thứ trong tuần')),
                ('noi_dung_nhiem_vu', models.TextField(blank=True, verbose_name='Khu vực / Nội dung nhiệm vụ')),
                ('bang_phan_cong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='nhatkyvanhanh.bangphancongnhiemvuhc', verbose_name='Bảng phân công')),
            ],
            options={
                'verbose_name': 'Chi tiết nhiệm vụ thứ trong tuần',
                'verbose_name_plural': 'Chi tiết nhiệm vụ thứ trong tuần',
                'ordering': ['stt', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bangphancongnhiemvuhc',
            constraint=models.UniqueConstraint(fields=('nha_may', 'nam', 'thang'), name='uq_bang_phan_cong_hc_nha_may_nam_thang'),
        ),
    ]
