# Generated by Django 5.2.17 on 2026-08-30 03:26

import django.db.models.deletion
import django.utils.timezone
import nhatkyvanhanh.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0002_bang_de_nghi_nhap_nguoi_de_nghi_and_more'),
        ('nhatkyvanhanh', '0054_sochuyendoitbthang_approval_fields'),
        ('quanlyvanhanh', '0025_auto_20260611_1511'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chitietchuyendoithietbi',
            options={'ordering': ['to_may', 'thu_tu', 'created_at'], 'verbose_name': 'Chi tiết chuyển đổi thiết bị tuần', 'verbose_name_plural': 'Chi tiết chuyển đổi thiết bị tuần'},
        ),
        migrations.AlterModelOptions(
            name='lanchuyendoithietbi',
            options={'ordering': ['thoi_gian', 'created_at'], 'verbose_name': 'Lần chuyển đổi thiết bị tuần', 'verbose_name_plural': 'Lần chuyển đổi thiết bị tuần'},
        ),
        migrations.AlterModelOptions(
            name='mauchuyendoithietbi',
            options={'ordering': ['to_may', 'thu_tu', 'created_at'], 'verbose_name': 'Mẫu chuyển đổi thiết bị tuần', 'verbose_name_plural': 'Mẫu chuyển đổi thiết bị tuần'},
        ),
        migrations.AlterModelOptions(
            name='sochuyendoithietbituan',
            options={'ordering': ['-nam', '-tuan', '-created_at'], 'verbose_name': 'Sổ theo dõi chuyển đổi thiết bị tuần', 'verbose_name_plural': 'Sổ theo dõi chuyển đổi thiết bị tuần'},
        ),
        migrations.RemoveConstraint(
            model_name='mauchuyendoithietbi',
            name='uq_mau_chuyen_doi_thiet_bi_nha_may_thiet_bi',
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='ghi_chu',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='lan_chuyen_doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='nhatkyvanhanh.lanchuyendoithietbi', verbose_name='Lần chuyển đổi'),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='nhom_thiet_bi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nhóm thiết bị'),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='thiet_bi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_chuyen_doi_thiet_bi', to='quanlyvanhanh.thietbi', verbose_name='Thiết bị'),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='thu_tu',
            field=models.PositiveIntegerField(default=1, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='to_may',
            field=models.CharField(choices=[('H1', 'Tổ máy H1'), ('H2', 'Tổ máy H2'), ('tu_dung', 'Tự dùng')], max_length=20, verbose_name='Tổ máy'),
        ),
        migrations.AlterField(
            model_name='chitietchuyendoithietbi',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('lam_viec', 'Làm việc'), ('du_phong', 'Dự phòng')], max_length=20, verbose_name='Trạng thái chuyển đổi'),
        ),
        migrations.AlterField(
            model_name='lanchuyendoithietbi',
            name='ghi_chu_chung',
            field=models.TextField(blank=True, verbose_name='Ghi chú chung'),
        ),
        migrations.AlterField(
            model_name='lanchuyendoithietbi',
            name='nguoi_thuc_hien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lan_chuyen_doi_thiet_bi_da_thuc_hien', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='lanchuyendoithietbi',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lan_chuyen_dois', to='nhatkyvanhanh.sochuyendoithietbituan', verbose_name='Sổ chuyển đổi tuần'),
        ),
        migrations.AlterField(
            model_name='lanchuyendoithietbi',
            name='thoi_gian',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian chuyển đổi'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='dang_su_dung',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='nhom_thiet_bi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nhóm thiết bị'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='thiet_bi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mau_chuyen_doi_thiet_bi', to='quanlyvanhanh.thietbi', verbose_name='Thiết bị liên kết'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='thu_tu',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='to_may',
            field=models.CharField(choices=[('H1', 'Tổ máy H1'), ('H2', 'Tổ máy H2'), ('tu_dung', 'Tự dùng')], max_length=20, verbose_name='Tổ máy'),
        ),
        migrations.AlterField(
            model_name='sochuyendoitbthang',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_tb_thang_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='ca_truc',
            field=models.CharField(choices=[('A', 'Ca A'), ('B', 'Ca B'), ('C', 'Ca C'), ('D', 'Ca D')], default='A', max_length=1, verbose_name='Ca trực'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='nam',
            field=models.PositiveSmallIntegerField(default=nhatkyvanhanh.models.base._current_year, verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_thiet_bi_tuan_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo sổ'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='tuan',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tuần'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='tuan_bat_dau',
            field=models.DateField(verbose_name='Ngày bắt đầu tuần'),
        ),
        migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='tuan_ket_thuc',
            field=models.DateField(verbose_name='Ngày kết thúc tuần'),
        ),
        migrations.AddConstraint(
            model_name='mauchuyendoithietbi',
            constraint=models.UniqueConstraint(fields=('nha_may', 'to_may', 'thiet_bi'), name='uq_mau_chuyen_doi_thiet_bi_nha_may_to_may_tb'),
        ),
    ]
