# Generated by Django 5.2.17 on 2026-08-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0055_alter_chitietchuyendoithietbi_options_and_more'),
        ('tochuc', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.AlterField(
            model_name='bangphancongnhiemvuhc',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bang_phan_cong_nhiem_vu_hc', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='mauchuyendoitbthang',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_tb_thang', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='mauchuyendoithietbi',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_chuyen_doi_thiet_bi', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='soantoandaugio',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_an_toan_dau_gio', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sobchcsonghinh',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_bchc_song_hinh', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sochuyendoitbthang',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_tb_thang', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sochuyendoithietbituan',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_chuyen_doi_thiet_bi_tuan', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sogiaonhancahc',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_hc', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sogiaonhancavh',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_giao_nhan_ca_vh', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sonhatkyvanhanh',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sonhatkyvanhanhdiesel',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_nhat_ky_van_hanh_diesel', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
            migrations.AlterField(
            model_name='sukien',
            name='nha_may',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_kiens', to='tochuc.nhamay', verbose_name='Nhà máy'),
            )],
        ),
    ]
