# Generated by Django 5.2.17 on 2026-08-31 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0056_alter_bangphancongnhiemvuhc_nha_may_and_more'),
        ('tochuc', '0003_shared_organization_directory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sochuyendoitbthang',
            name='uq_so_chuyen_doi_tb_thang_nha_may_nam_thang_ca',
        ),
        migrations.AddConstraint(
            model_name='sochuyendoitbthang',
            constraint=models.UniqueConstraint(fields=('nha_may', 'nam', 'thang'), name='uq_so_chuyen_doi_tb_thang_nha_may_nam_thang'),
        ),
    ]
