# Generated by Django 5.2.17 on 2026-09-03 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0057_remove_sochuyendoitbthang_uq_so_chuyen_doi_tb_thang_nha_may_nam_thang_ca_and_more'),
        ('quanlyvanhanh', '0026_enable_unaccent_extension'),
        ('tochuc', '0008_normalize_root_unit_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='ghi_chu_van_hanh_bo_sung',
            field=models.TextField(blank=True, verbose_name='Ghi chú vận hành bổ sung'),
        ),
        migrations.CreateModel(
            name='MauTrangThaiThietBiCa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_mau', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('phien_ban', models.PositiveIntegerField(default=1, verbose_name='Phiên bản')),
                ('dang_ap_dung', models.BooleanField(default=False, verbose_name='Đang áp dụng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_trang_thai_thiet_bi_ca_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_trang_thai_thiet_bi_ca', to='tochuc.nhamay', verbose_name='Nhà máy')),
            ],
            options={
                'verbose_name': 'Mẫu trạng thái thiết bị ca',
                'verbose_name_plural': 'Mẫu trạng thái thiết bị ca',
                'ordering': ['nha_may__ten_nha_may', '-phien_ban'],
                'permissions': [('activate_mautrangthaithietbica', 'Có quyền kích hoạt mẫu trạng thái thiết bị ca')],
            },
        ),
        migrations.CreateModel(
            name='NhomMauTrangThaiThietBiCa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_nhom', models.SlugField(max_length=80, verbose_name='Mã nhóm')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('thu_tu', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('mau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhom_thiet_bi', to='nhatkyvanhanh.mautrangthaithietbica', verbose_name='Mẫu')),
            ],
            options={
                'verbose_name': 'Nhóm mẫu trạng thái thiết bị ca',
                'verbose_name_plural': 'Nhóm mẫu trạng thái thiết bị ca',
                'ordering': ['thu_tu', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietMauTrangThaiThietBiCa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_hien_thi', models.CharField(max_length=255, verbose_name='Mã hiển thị')),
                ('trang_thai_mac_dinh', models.CharField(choices=[('dong', 'Đóng'), ('cat', 'Cắt'), ('cat_vtcl', 'Cắt VTCL'), ('khac', 'Khác')], default='dong', max_length=16, verbose_name='Trạng thái mặc định')),
                ('ghi_chu_mac_dinh', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú mặc định')),
                ('thu_tu', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('thiet_bi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_mau_trang_thai_ca', to='quanlyvanhanh.thietbi', verbose_name='Thiết bị trong danh mục')),
                ('nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thiet_bi', to='nhatkyvanhanh.nhommautrangthaithietbica', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Chi tiết mẫu trạng thái thiết bị ca',
                'verbose_name_plural': 'Chi tiết mẫu trạng thái thiết bị ca',
                'ordering': ['thu_tu', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mautrangthaithietbica',
            constraint=models.UniqueConstraint(fields=('nha_may', 'phien_ban'), name='uq_mau_trang_thai_tb_ca_nha_may_phien_ban'),
        ),
        migrations.AddConstraint(
            model_name='mautrangthaithietbica',
            constraint=models.UniqueConstraint(condition=models.Q(('dang_ap_dung', True)), fields=('nha_may',), name='uq_mau_trang_thai_tb_ca_dang_ap_dung'),
        ),
        migrations.AddConstraint(
            model_name='nhommautrangthaithietbica',
            constraint=models.UniqueConstraint(fields=('mau', 'ma_nhom'), name='uq_nhom_mau_tb_ca_ma_nhom'),
        ),
        migrations.AddConstraint(
            model_name='chitietmautrangthaithietbica',
            constraint=models.UniqueConstraint(fields=('nhom', 'ma_hien_thi'), name='uq_chi_tiet_mau_tb_ca_ma'),
        ),
    ]
