# Generated by Django 5.2.17 on 2026-09-04 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0059_seed_device_status_templates'),
        ('tochuc', '0008_normalize_root_unit_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MauTomLuocGiaoCaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_mau', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('phien_ban', models.PositiveIntegerField(default=1, verbose_name='Phiên bản')),
                ('dang_ap_dung', models.BooleanField(default=False, verbose_name='Đang áp dụng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mau_tom_luoc_giao_ca_vh_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_tom_luoc_giao_ca_vh', to='tochuc.nhamay', verbose_name='Nhà máy')),
            ],
            options={
                'verbose_name': 'Mẫu tóm lược giao ca vận hành',
                'verbose_name_plural': 'Mẫu tóm lược giao ca vận hành',
                'ordering': ['nha_may__ten_nha_may', '-phien_ban'],
                'permissions': [('activate_mautomluocgiaocavh', 'Có quyền kích hoạt mẫu tóm lược giao ca vận hành')],
            },
        ),
        migrations.CreateModel(
            name='HangMucMauTomLuocGiaoCaVH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_hang_muc', models.CharField(max_length=255, verbose_name='Hạng mục')),
                ('noi_dung_mac_dinh', models.TextField(blank=True, verbose_name='Nội dung mặc định')),
                ('ghi_chu_mac_dinh', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú mặc định')),
                ('bat_buoc', models.BooleanField(default=False, verbose_name='Bắt buộc')),
                ('thu_tu', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('mau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hang_muc', to='nhatkyvanhanh.mautomluocgiaocavh', verbose_name='Mẫu')),
            ],
            options={
                'verbose_name': 'Hạng mục mẫu tóm lược giao ca vận hành',
                'verbose_name_plural': 'Hạng mục mẫu tóm lược giao ca vận hành',
                'ordering': ['thu_tu', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sogiaonhancavh',
            name='mau_tom_luoc_nguon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_giao_nhan_ca_vh', to='nhatkyvanhanh.mautomluocgiaocavh', verbose_name='Mẫu tóm lược nguồn'),
        ),
        migrations.AddConstraint(
            model_name='mautomluocgiaocavh',
            constraint=models.UniqueConstraint(fields=('nha_may', 'phien_ban'), name='uq_mau_tom_luoc_vh_nha_may_phien_ban'),
        ),
        migrations.AddConstraint(
            model_name='mautomluocgiaocavh',
            constraint=models.UniqueConstraint(condition=models.Q(('dang_ap_dung', True)), fields=('nha_may',), name='uq_mau_tom_luoc_vh_dang_ap_dung'),
        ),
        migrations.AddConstraint(
            model_name='hangmucmautomluocgiaocavh',
            constraint=models.UniqueConstraint(fields=('mau', 'ten_hang_muc'), name='uq_hang_muc_mau_tom_luoc_vh'),
        ),
    ]
