# Generated by Django 5.2.17 on 2026-09-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0060_mautomluocgiaocavh_hangmucmautomluocgiaocavh_and_more'),
        ('tochuc', '0008_normalize_root_unit_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhansusogiaonhancavh',
            name='ma_nhan_vien',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mã nhân viên'),
        ),
        migrations.AddField(
            model_name='nhansusogiaonhancavh',
            name='nhan_su',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_su_so_giao_nhan_ca_vh', to='tochuc.nhansu', verbose_name='Nhân sự'),
        ),
    ]
