# Generated by Django 5.2.17 on 2026-09-11 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0062_backfill_shift_staff_identity'),
        ('tochuc', '0008_normalize_root_unit_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MauNoiDungVanHanh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_mau', models.CharField(db_index=True, help_text='Mã định danh duy nhất của mẫu (ví dụ: hoa_luoi, dung_may, lenh_dieu_do_p)', max_length=50, verbose_name='Mã mẫu')),
                ('ten_mau', models.CharField(help_text='Tên hiển thị trực quan của mẫu câu', max_length=150, verbose_name='Tên mẫu')),
                ('nhom_mau', models.CharField(choices=[('khoi_dong_hoa_luoi', 'Khởi động & Hòa lưới'), ('dung_tach_may', 'Dừng & Tách lưới'), ('dong_cat_mc', 'Thao tác Đóng/Cắt MC'), ('phieu_thao_tac', 'Phiếu thao tác'), ('phieu_cong_tac', 'Phiếu công tác'), ('dieu_do_p', 'Thay đổi công suất'), ('cong_tac_co_lap', 'Công tác & Cô lập'), ('thuy_van_van_tran', 'Thủy văn & Van tràn'), ('khac', 'Khác')], default='khac', max_length=50, verbose_name='Nhóm nghiệp vụ')),
                ('dinh_dang_tieu_de', models.CharField(help_text='Cú pháp tiêu đề chứa placeholders {ten_tham_so}', max_length=255, verbose_name='Định dạng tiêu đề')),
                ('dinh_dang_mau', models.TextField(help_text='Cú pháp nội dung chứa placeholders {ten_tham_so}', verbose_name='Định dạng nội dung mẫu')),
                ('danh_sach_tham_so', models.JSONField(blank=True, default=list, help_text='Cấu hình danh sách các trường tham số điền nhanh (JSON schema)', verbose_name='Danh sách tham số')),
                ('thu_tu', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('phien_ban', models.PositiveIntegerField(default=1, verbose_name='Phiên bản')),
                ('dang_ap_dung', models.BooleanField(default=True, help_text='Chỉ có duy nhất 1 phiên bản được áp dụng cho mỗi mã mẫu trong cùng phạm vi', verbose_name='Đang áp dụng')),
                ('la_mau_he_thong', models.BooleanField(default=False, help_text='Mẫu mặc định của toàn hệ thống, không thể xóa', verbose_name='Mẫu hệ thống')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoi_cap_nhat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mau_noi_dung_vh_da_cap_nhat', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mau_noi_dung_vh_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('nha_may', models.ForeignKey(blank=True, help_text='Để trống nếu là mẫu chung hệ thống', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mau_noi_dung_van_hanh', to='tochuc.nhamay', verbose_name='Nhà máy')),
            ],
            options={
                'verbose_name': 'Mẫu nội dung vận hành',
                'verbose_name_plural': 'Mẫu nội dung vận hành',
                'ordering': ['thu_tu', 'ma_mau', '-phien_ban'],
                'permissions': [('activate_maunoidungvanhanh', 'Có quyền kích hoạt mẫu nội dung vận hành')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('nha_may__isnull', True)), fields=('ma_mau', 'phien_ban'), name='uq_mau_noi_dung_vh_global_ma_phien_ban'), models.UniqueConstraint(condition=models.Q(('nha_may__isnull', False)), fields=('nha_may', 'ma_mau', 'phien_ban'), name='uq_mau_noi_dung_vh_plant_ma_phien_ban'), models.UniqueConstraint(condition=models.Q(('dang_ap_dung', True), ('nha_may__isnull', True)), fields=('ma_mau',), name='uq_mau_noi_dung_vh_global_active'), models.UniqueConstraint(condition=models.Q(('dang_ap_dung', True), ('nha_may__isnull', False)), fields=('nha_may', 'ma_mau'), name='uq_mau_noi_dung_vh_plant_active')],
            },
        ),
    ]
