# Generated manually for seeding 14 standardized global shift command templates

from django.db import migrations

TEMPLATES_DATA = [   {   'danh_sach_tham_so': [   {   'default': 'H1',
                                     'key': 'to_may',
                                     'label': 'Tổ máy',
                                     'optionsSource': 'plantUnits',
                                     'required': True,
                                     'type': 'select'},
                                 {   'key': 'cong_suat',
                                     'label': 'Công suất P (MW)',
                                     'min': 0,
                                     'required': True,
                                     'type': 'number'},
                                 {   'default': 'A0',
                                     'key': 'nguoi_ra_lenh',
                                     'label': 'Người ra lệnh',
                                     'options': ['A0', 'A3', 'B3', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Hòa lưới tổ máy {to_may}, phát {cong_suat} MW / người ra lệnh là {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Chạy máy {to_may}',
        'ma_mau': 'hoa_luoi',
        'nhom_mau': 'khoi_dong_hoa_luoi',
        'ten_mau': 'Hòa lưới tổ máy',
        'thu_tu': 1},
    {   'danh_sach_tham_so': [   {   'default': 'H1',
                                     'key': 'to_may',
                                     'label': 'Tổ máy',
                                     'optionsSource': 'plantUnits',
                                     'required': True,
                                     'type': 'select'},
                                 {   'default': 'A0',
                                     'key': 'nguoi_ra_lenh',
                                     'label': 'Người ra lệnh',
                                     'options': ['A0', 'A3', 'B3', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Tách máy {to_may}, dừng tổ máy an toàn theo lệnh điều độ {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Dừng máy {to_may}',
        'ma_mau': 'dung_may',
        'nhom_mau': 'dung_tach_may',
        'ten_mau': 'Dừng & tách máy',
        'thu_tu': 2},
    {   'danh_sach_tham_so': [   {   'default': 'H1',
                                     'key': 'to_may',
                                     'label': 'Tổ máy',
                                     'optionsSource': 'plantUnits',
                                     'required': True,
                                     'type': 'select'},
                                 {   'default': 'A0',
                                     'key': 'nguoi_ra_lenh',
                                     'label': 'Người ra lệnh',
                                     'options': ['A0', 'A3', 'B38', 'B3', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Dừng dự phòng tổ máy {to_may} theo lệnh điều độ {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Dừng dự phòng máy {to_may}',
        'ma_mau': 'dung_du_phong',
        'nhom_mau': 'dung_tach_may',
        'ten_mau': 'Dừng dự phòng tổ máy',
        'thu_tu': 3},
    {   'danh_sach_tham_so': [   {   'default': 'H1',
                                     'key': 'to_may',
                                     'label': 'Tổ máy',
                                     'optionsSource': 'plantUnits',
                                     'required': True,
                                     'type': 'select'},
                                 {   'default': 'A0',
                                     'key': 'nguoi_ra_lenh',
                                     'label': 'Người ra lệnh',
                                     'options': ['A0', 'A3', 'B38', 'B3', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Tách tổ máy {to_may} theo lệnh điều độ {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Tách máy {to_may}',
        'ma_mau': 'tach_to_may',
        'nhom_mau': 'dung_tach_may',
        'ten_mau': 'Tách tổ máy',
        'thu_tu': 4},
    {   'danh_sach_tham_so': [   {   'default': 'T1',
                                     'key': 'may_bien_ap',
                                     'label': 'Máy biến áp',
                                     'options': ['T1', 'T2'],
                                     'optionsSource': 'transformers',
                                     'required': True,
                                     'type': 'select'},
                                 {   'default': 'A3',
                                     'key': 'nguoi_ra_lenh',
                                     'label': 'Người ra lệnh',
                                     'options': ['A3', 'B38', 'A0', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Tách máy biến áp {may_bien_ap} theo lệnh điều độ {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Tách MBA {may_bien_ap}',
        'ma_mau': 'tach_mba',
        'nhom_mau': 'dung_tach_may',
        'ten_mau': 'Tách máy biến áp',
        'thu_tu': 5},
    {   'danh_sach_tham_so': [   {   'default': 'đóng',
                                     'key': 'hanh_dong',
                                     'label': 'Hành động',
                                     'options': ['đóng', 'cắt'],
                                     'required': True,
                                     'type': 'select'},
                                 {'key': 'ma_thiet_bi', 'label': 'Mã máy cắt', 'required': True, 'type': 'device'},
                                 {   'default': 'A3',
                                     'key': 'nguoi_ra_lenh',
                                     'label': 'Người ra lệnh',
                                     'options': ['A3', 'B38', 'A0', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Thao tác {hanh_dong} máy cắt {ma_thiet_bi}. Người ra lệnh: {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Thao tác MC {ma_thiet_bi}',
        'ma_mau': 'dong_cat_mc',
        'nhom_mau': 'dong_cat_mc',
        'ten_mau': 'Thao tác Đóng/Cắt máy cắt',
        'thu_tu': 6},
    {   'danh_sach_tham_so': [   {   'default': 'đóng',
                                     'key': 'hanh_dong',
                                     'label': 'Hành động',
                                     'options': ['đóng', 'cắt'],
                                     'required': True,
                                     'type': 'select'},
                                 {'key': 'ma_thiet_bi', 'label': 'Mã máy cắt', 'required': True, 'type': 'device'},
                                 {   'default': 'A3',
                                     'key': 'nguoi_nhan_bao',
                                     'label': 'Điều độ nhận báo',
                                     'options': ['A3', 'B38', 'A0', 'Trưởng ca'],
                                     'required': True,
                                     'type': 'select'}],
        'dinh_dang_mau': 'Báo cáo điều độ {nguoi_nhan_bao} đã thao tác {hanh_dong} tốt máy cắt {ma_thiet_bi}.',
        'dinh_dang_tieu_de': 'Báo hoàn thành thao tác MC {ma_thiet_bi}',
        'ma_mau': 'bao_hoan_thanh_mc',
        'nhom_mau': 'dong_cat_mc',
        'ten_mau': 'Báo hoàn thành thao tác MC',
        'thu_tu': 7},
    {   'danh_sach_tham_so': [   {   'default': 'A3',
                                     'key': 'dieu_do',
                                     'label': 'Cấp điều độ',
                                     'options': ['A3', 'B38', 'A0'],
                                     'required': True,
                                     'type': 'select'},
                                 {   'key': 'so_phieu',
                                     'label': 'Số phiếu thao tác',
                                     'maxLength': 50,
                                     'placeholder': 'Ví dụ: 12/PTT-SH',
                                     'required': True,
                                     'type': 'text'}],
        'dinh_dang_mau': 'Điều độ {dieu_do} lệnh thực hiện Phiếu thao tác số {so_phieu}.',
        'dinh_dang_tieu_de': 'Thực hiện PTT số {so_phieu}',
        'ma_mau': 'phieu_thao_tac',
        'nhom_mau': 'phieu_thao_tac',
        'ten_mau': 'Thực hiện Phiếu thao tác',
        'thu_tu': 8},
    {   'danh_sach_tham_so': [   {   'default': 'A3',
                                     'key': 'dieu_do',
                                     'label': 'Cấp điều độ',
                                     'options': ['A3', 'B38', 'A0'],
                                     'required': True,
                                     'type': 'select'},
                                 {   'key': 'so_phieu',
                                     'label': 'Số phiếu thao tác',
                                     'maxLength': 50,
                                     'placeholder': 'Ví dụ: 12/PTT-SH',
                                     'required': True,
                                     'type': 'text'}],
        'dinh_dang_mau': 'Báo cáo điều độ {dieu_do} đã thực hiện hoàn thành Phiếu thao tác số {so_phieu}.',
        'dinh_dang_tieu_de': 'Báo hoàn thành PTT số {so_phieu}',
        'ma_mau': 'bao_hoan_thanh_ptt',
        'nhom_mau': 'phieu_thao_tac',
        'ten_mau': 'Báo hoàn thành Phiếu thao tác',
        'thu_tu': 9},
    {   'danh_sach_tham_so': [   {   'key': 'so_phieu',
                                     'label': 'Số phiếu công tác (PCT)',
                                     'maxLength': 50,
                                     'placeholder': 'Ví dụ: 05/PCT-SH',
                                     'required': True,
                                     'type': 'text'}],
        'dinh_dang_mau': 'Cấp Phiếu công tác số {so_phieu}.',
        'dinh_dang_tieu_de': 'Cấp PCT số {so_phieu}',
        'ma_mau': 'cap_phieu_cong_tac',
        'nhom_mau': 'phieu_cong_tac',
        'ten_mau': 'Cấp Phiếu công tác',
        'thu_tu': 10},
    {   'danh_sach_tham_so': [   {   'key': 'so_phieu',
                                     'label': 'Số phiếu công tác (PCT)',
                                     'maxLength': 50,
                                     'placeholder': 'Số PCT vừa cấp hoặc số khác',
                                     'required': True,
                                     'type': 'text'}],
        'dinh_dang_mau': 'Cho phép đơn vị vào làm việc theo Phiếu công tác số {so_phieu}.',
        'dinh_dang_tieu_de': 'Cho phép làm việc theo PCT số {so_phieu}',
        'ma_mau': 'cho_phep_vao_lam_viec',
        'nhom_mau': 'phieu_cong_tac',
        'ten_mau': 'Cho phép vào làm việc',
        'thu_tu': 11},
    {   'danh_sach_tham_so': [   {   'default': 'A0',
                                     'key': 'dieu_do',
                                     'label': 'Cấp điều độ',
                                     'options': ['A0', 'A3'],
                                     'required': True,
                                     'type': 'select'},
                                 {   'default': 'H1',
                                     'key': 'to_may',
                                     'label': 'Tổ máy',
                                     'optionsSource': 'plantUnits',
                                     'required': True,
                                     'type': 'select'},
                                 {   'key': 'p',
                                     'label': 'Công suất P (MW)',
                                     'min': 0,
                                     'required': True,
                                     'type': 'number'}],
        'dinh_dang_mau': 'Điều độ {dieu_do} lệnh thay đổi công suất tổ máy {to_may}: P = {p} MW.',
        'dinh_dang_tieu_de': 'Lệnh điều độ thay đổi công suất',
        'ma_mau': 'lenh_dieu_do_p',
        'nhom_mau': 'dieu_do_p',
        'ten_mau': 'Lệnh điều độ thay đổi công suất',
        'thu_tu': 12},
    {   'danh_sach_tham_so': [   {'key': 'thiet_bi', 'label': 'Thiết bị', 'required': True, 'type': 'device'},
                                 {   'default': 'PCT',
                                     'key': 'loai_phieu',
                                     'label': 'Loại phiếu',
                                     'options': ['PCT', 'LCT'],
                                     'required': True,
                                     'type': 'select'},
                                 {   'key': 'so_phieu',
                                     'label': 'Số phiếu/lệnh',
                                     'maxLength': 50,
                                     'required': True,
                                     'type': 'text'}],
        'dinh_dang_mau': 'Đã cô lập an toàn thiết bị {thiet_bi}, bàn giao cho đơn vị công tác theo {loai_phieu} số '
                         '{so_phieu}.',
        'dinh_dang_tieu_de': 'Cô lập bàn giao {thiet_bi}',
        'ma_mau': 'co_lap_ban_giao',
        'nhom_mau': 'cong_tac_co_lap',
        'ten_mau': 'Cô lập & Bàn giao thiết bị',
        'thu_tu': 13},
    {   'danh_sach_tham_so': [   {   'default': 'nâng',
                                     'key': 'hanh_dong',
                                     'label': 'Hành động',
                                     'options': ['nâng', 'hạ', 'đóng hoàn toàn'],
                                     'required': True,
                                     'type': 'select'},
                                 {   'default': '1',
                                     'key': 'so_van',
                                     'label': 'Số cửa van',
                                     'optionsSource': 'spillwayGates',
                                     'required': True,
                                     'type': 'select'},
                                 {   'key': 'do_mo',
                                     'label': 'Độ mở (m)',
                                     'min': 0,
                                     'required': True,
                                     'step': 0.1,
                                     'type': 'number'},
                                 {   'key': 'q_xa',
                                     'label': 'Lưu lượng xả (m³/s)',
                                     'min': 0,
                                     'required': True,
                                     'step': 0.1,
                                     'type': 'number'},
                                 {'key': 'nguoi_ra_lenh', 'label': 'Người ra lệnh', 'required': True, 'type': 'text'}],
        'dinh_dang_mau': 'Thao tác {hanh_dong} cửa van cung số {so_van} độ mở {do_mo} m, lưu lượng qua tràn {q_xa} '
                         'm3/s theo lệnh {nguoi_ra_lenh}.',
        'dinh_dang_tieu_de': 'Thao tác van cung số {so_van}',
        'ma_mau': 'thao_tac_van_tran',
        'nhom_mau': 'thuy_van_van_tran',
        'ten_mau': 'Thao tác van cung tràn',
        'thu_tu': 14}]


def seed_default_templates(apps, schema_editor):
    MauNoiDungVanHanh = apps.get_model('nhatkyvanhanh', 'MauNoiDungVanHanh')
    for item in TEMPLATES_DATA:
        # Sử dụng khóa lookup chính xác: nha_may=None, ma_mau=..., phien_ban=1
        MauNoiDungVanHanh.objects.update_or_create(
            nha_may=None,
            ma_mau=item['ma_mau'],
            phien_ban=1,
            defaults={
                'ten_mau': item['ten_mau'],
                'nhom_mau': item['nhom_mau'],
                'dinh_dang_tieu_de': item['dinh_dang_tieu_de'],
                'dinh_dang_mau': item['dinh_dang_mau'],
                'danh_sach_tham_so': item['danh_sach_tham_so'],
                'thu_tu': item['thu_tu'],
                'dang_ap_dung': True,
                'la_mau_he_thong': True,
                'ghi_chu': 'Mẫu chuẩn hóa hệ thống ban đầu (Giai đoạn 1)',
            }
        )


def reverse_default_templates(apps, schema_editor):
    MauNoiDungVanHanh = apps.get_model('nhatkyvanhanh', 'MauNoiDungVanHanh')
    MauNoiDungVanHanh.objects.filter(nha_may=None, la_mau_he_thong=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nhatkyvanhanh', '0063_create_mau_noi_dung_van_hanh'),
    ]

    operations = [
        migrations.RunPython(seed_default_templates, reverse_default_templates),
    ]
