# Generated by Django 3.2.25 on 2025-09-26 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_mobile_user', models.BooleanField(default=True, help_text='Đánh dấu user có thể đăng nhập từ mobile app')),
                ('avatar', models.ImageField(blank=True, help_text='Hình ảnh đại diện của user', null=True, upload_to='avatars/')),
                ('chuc_danh', models.CharField(blank=True, help_text='Chức danh công việc của user', max_length=100, null=True)),
                ('chu_ky', models.ImageField(blank=True, help_text='Hình ảnh chữ ký của user', null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Liên kết với User model', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
                'db_table': 'core_user_profile',
            },
        ),
    ]
