# Generated by Django 3.2.25 on 2025-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ho',
            field=models.CharField(blank=True, help_text='Họ của user', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ho_ten',
            field=models.CharField(blank=True, help_text='Họ và tên đầy đủ của user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ten',
            field=models.CharField(blank=True, help_text='Tên của user', max_length=100, null=True),
        ),
    ]
