# Generated by Django 3.2.25 on 2025-09-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250926_1530'),
    ]

    operations = [
    ]
