# Generated by Django 3.2.25 on 2025-09-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khovattu', '0001_initial'),
        ('core', '0005_auto_20250926_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_all_factories',
            field=models.BooleanField(default=False, help_text='User có quyền truy cập tất cả nhà máy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nha_may',
            field=models.ForeignKey(blank=True, help_text='Nhà máy mà user được phép truy cập (null = tất cả nhà máy)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='khovattu.bang_nha_may'),
        ),
    ]
