# Generated by Django 5.1 on 2025-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250928_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_materials',
            field=models.BooleanField(default=False, help_text='Có quyền thêm vật tư mới'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_export_request',
            field=models.BooleanField(default=False, help_text='Có quyền phê duyệt đề nghị xuất'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_export_request',
            field=models.BooleanField(default=False, help_text='Có quyền tạo đề nghị xuất'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_materials',
            field=models.BooleanField(default=False, help_text='Có quyền xóa vật tư'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_inventory',
            field=models.BooleanField(default=False, help_text='Có quyền sửa thông tin kiểm kê'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_materials',
            field=models.BooleanField(default=False, help_text='Có quyền sửa thông tin vật tư'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_export_excel',
            field=models.BooleanField(default=True, help_text='Có quyền export dữ liệu ra Excel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_import_excel',
            field=models.BooleanField(default=False, help_text='Có quyền import dữ liệu từ Excel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_inventory',
            field=models.BooleanField(default=True, help_text='Có quyền xem kiểm kê'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_materials',
            field=models.BooleanField(default=True, help_text='Có quyền xem danh sách vật tư'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=True, help_text='Có quyền xem báo cáo thống kê'),
        ),
    ]
