# Generated by Django 3.2.25 on 2025-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_can_add_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_import_request',
            field=models.BooleanField(default=False, help_text='Có quyền phê duyệt đề nghị nhập'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_import_request',
            field=models.BooleanField(default=False, help_text='Có quyền tạo đề nghị nhập'),
        ),
    ]
