# Generated by Django 3.2.25 on 2025-10-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251003_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_export_requests',
            field=models.BooleanField(default=True, help_text='Có quyền xem đề nghị xuất'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_import_requests',
            field=models.BooleanField(default=True, help_text='Có quyền xem đề nghị nhập'),
        ),
    ]
