# Generated by Django 5.1 on 2026-04-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_operation_event_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen tao so giao nhan ca van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen xoa so giao nhan ca van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen sua so giao nhan ca van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_receive_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen ky nhan ca trong so giao nhan ca van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_shift_handover_logs',
            field=models.BooleanField(default=True, help_text='Co quyen xem so giao nhan ca van hanh'),
        ),
    ]
