# Generated by Django 5.1 on 2026-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_can_create_shift_handover_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_admin_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen tao so giao nhan ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_admin_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen xoa so giao nhan ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_admin_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen sua so giao nhan ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_receive_admin_shift_handover_logs',
            field=models.BooleanField(default=False, help_text='Co quyen ky nhan ca trong so giao nhan ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_admin_shift_handover_logs',
            field=models.BooleanField(default=True, help_text='Co quyen xem so giao nhan ca hanh chinh'),
        ),
    ]
