# Generated by Django 5.1 on 2026-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_can_create_admin_shift_handover_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_confirm_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen xac nhan so nhat ky van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen tao so nhat ky van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen xoa so nhat ky van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen sua so nhat ky van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_operation_logbooks',
            field=models.BooleanField(default=True, help_text='Co quyen xem so nhat ky van hanh'),
        ),
    ]
