# Generated by Django 5.1 on 2026-04-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_can_confirm_operation_logbooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_diesel_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen tao so nhat ky van hanh Diesel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_diesel_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen xoa so nhat ky van hanh Diesel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_diesel_operation_logbooks',
            field=models.BooleanField(default=False, help_text='Co quyen sua so nhat ky van hanh Diesel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_diesel_operation_logbooks',
            field=models.BooleanField(default=True, help_text='Co quyen xem so nhat ky van hanh Diesel'),
        ),
    ]
