# Generated by Django 5.1 on 2026-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_quanlyvanhanh_equipment_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_hydrology_data',
            field=models.BooleanField(default=False, help_text='Co quyen them dong bo du lieu thuy van va san xuat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_hydrology_data',
            field=models.BooleanField(default=False, help_text='Co quyen xoa du lieu thuy van va san xuat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_hydrology_data',
            field=models.BooleanField(default=False, help_text='Co quyen sua du lieu thuy van va san xuat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_hydrology_data',
            field=models.BooleanField(default=True, help_text='Co quyen xem du lieu thuy van va san xuat'),
        ),
    ]
