# Generated by Django 5.1 on 2026-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_can_create_hydrology_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_update_realtime_hydrology',
            field=models.BooleanField(default=False, help_text='Co quyen bat/tat va cap nhat tay du lieu realtime'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_realtime_hydrology',
            field=models.BooleanField(default=True, help_text='Co quyen xem trang realtime Song Hinh va Vinh Son'),
        ),
    ]
