# Generated by Django 5.1 on 2026-05-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_can_update_realtime_hydrology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_bchc_song_hinh',
            field=models.BooleanField(default=False, help_text='Co quyen tao/dong bo so BCHC Song Hinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_bchc_song_hinh',
            field=models.BooleanField(default=False, help_text='Co quyen sua so BCHC Song Hinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_bchc_song_hinh',
            field=models.BooleanField(default=True, help_text='Co quyen xem so BCHC Song Hinh'),
        ),
    ]
