# Generated by Django 5.1 on 2026-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_bchc_song_hinh_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_so_an_toan_dau_gio',
            field=models.BooleanField(default=False, help_text='Co quyen xoa so an toan dau gio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_so_an_toan_dau_gio',
            field=models.BooleanField(default=False, help_text='Co quyen sua so an toan dau gio'),
        ),
    ]
