# Generated by Django 5.1 on 2026-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_can_delete_so_an_toan_dau_gio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_so_an_toan_dau_gio',
            field=models.BooleanField(default=True, help_text='Co quyen xem so an toan dau gio'),
        ),
    ]
