# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userprofile_can_view_so_an_toan_dau_gio"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_view_weekly_equipment_switch_logs",
            field=models.BooleanField(
                default=True,
                help_text="Co quyen xem so chuyen doi thiet bi tuan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_create_weekly_equipment_switch_logs",
            field=models.BooleanField(
                default=False,
                help_text="Co quyen tao so chuyen doi thiet bi tuan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_edit_weekly_equipment_switch_logs",
            field=models.BooleanField(
                default=False,
                help_text="Co quyen sua so chuyen doi thiet bi tuan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_delete_weekly_equipment_switch_logs",
            field=models.BooleanField(
                default=False,
                help_text="Co quyen xoa so chuyen doi thiet bi tuan",
            ),
        ),
    ]
