# Generated by Django 5.1 on 2026-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprofile_weekly_equipment_switch_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Co quyen tao so chuyen doi TB thang'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Co quyen xoa so chuyen doi TB thang'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Co quyen sua so chuyen doi TB thang'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_monthly_equipment_switch_logs',
            field=models.BooleanField(default=True, help_text='Co quyen xem so chuyen doi TB thang'),
        ),
    ]
