# Generated by Django 5.1 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_can_create_monthly_equipment_switch_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_hydrology_settings',
            field=models.BooleanField(default=False, help_text='Co quyen sua thong so thuy van cai dat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_hydrology_settings',
            field=models.BooleanField(default=False, help_text='Co quyen xem thong so thuy van cai dat'),
        ),
    ]
