# Generated by Django 5.1 on 2026-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_can_edit_hydrology_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_ai_tools',
            field=models.BooleanField(default=False, help_text='Co quyen su dung tro ly AI va cac cong cu phan tich'),
        ),
    ]
