# Generated by Django 3.2.25 on 2026-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userprofile_can_use_ai_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_leadership_directives',
            field=models.BooleanField(default=False, help_text='Co quyen nhap chi dao su kien van hanh'),
        ),
    ]
