# Generated by Django 5.1 on 2026-05-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_can_edit_leadership_directives'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shift_handover_directives',
            field=models.BooleanField(default=False, help_text='Co quyen tao luu y chi dao so giao nhan ca van hanh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_shift_handover_directives',
            field=models.BooleanField(default=False, help_text='Co quyen xem luu y chi dao so giao nhan ca van hanh'),
        ),
    ]
