# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userprofile_can_create_shift_handover_directives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_use_ai_documents",
            field=models.BooleanField(default=False, help_text="Co quyen su dung kho tai lieu AI va tim kiem RAG"),
        ),
    ]
