# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_userprofile_can_use_ai_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_view_operation_thresholds",
            field=models.BooleanField(default=False, help_text="Co quyen xem nguong thong so van hanh"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_create_operation_thresholds",
            field=models.BooleanField(default=False, help_text="Co quyen them nguong thong so van hanh"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_edit_operation_thresholds",
            field=models.BooleanField(default=False, help_text="Co quyen sua nguong thong so van hanh"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_delete_operation_thresholds",
            field=models.BooleanField(default=False, help_text="Co quyen xoa nguong thong so van hanh"),
        ),
    ]
