# Generated by Django 3.2.25 on 2026-06-19 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userprofile_operation_threshold_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='Loại hành động', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Địa chỉ IP', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Thông tin trình duyệt/thiết bị')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Thời gian ghi nhận')),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng thực hiện', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-timestamp'],
            },
        ),
    ]
