# Generated by Django 3.2.25 on 2026-06-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nhập tên vai trò (ví dụ: Trưởng ca vận hành, Nhân viên hành chính...)', max_length=100, unique=True, verbose_name='Tên vai trò')),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về chức trách hoặc quyền hạn của vai trò.', null=True, verbose_name='Mô tả vai trò')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Cấu hình quyền dạng JSON (được cập nhật tự động từ form Admin).', verbose_name='Danh sách quyền (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vai trò người dùng',
                'verbose_name_plural': 'Danh sách vai trò',
                'db_table': 'core_user_role',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Chọn vai trò để tự động đồng bộ quyền. Để trống nếu muốn tự tích chọn quyền thủ công (Tùy chỉnh).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.userrole', verbose_name='Vai trò'),
        ),
    ]
