# Generated by Django 3.2.25 on 2026-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20260619_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_receive_alert_notifications',
            field=models.BooleanField(default=True, help_text='Quyết định người dùng có nhận được thông báo Toast khi thông số vận hành vượt ngưỡng hoặc gặp sự cố hay không.', verbose_name='Nhận thông báo cảnh báo thông số'),
        ),
    ]
