# Generated by Django 5.2.17 on 2026-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userprofile_shift_handover_object_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền duyệt, áp dụng và khóa lịch trực ca'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền tạo và sinh lịch trực ca'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền xóa lịch trực ca dự thảo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền sửa lịch trực ca dự thảo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_export_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền xuất lịch trực ca'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_shift_roster',
            field=models.BooleanField(default=False, help_text='Có quyền quản lý kíp và thành viên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_submit_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền gửi duyệt lịch trực ca'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_shift_schedule',
            field=models.BooleanField(default=False, help_text='Có quyền xem lịch trực ca'),
        ),
    ]
