# Generated by Django 5.2.17 on 2026-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_userprofile_can_approve_shift_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_admin_shift_duty_rosters',
            field=models.BooleanField(default=False, help_text='Co quyen tao bang phan cong nhiem vu ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_admin_shift_duty_rosters',
            field=models.BooleanField(default=False, help_text='Co quyen xoa bang phan cong nhiem vu ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_admin_shift_duty_rosters',
            field=models.BooleanField(default=False, help_text='Co quyen sua bang phan cong nhiem vu ca hanh chinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_admin_shift_duty_rosters',
            field=models.BooleanField(default=True, help_text='Co quyen xem bang phan cong nhiem vu ca hanh chinh'),
        ),
    ]
