# Generated by Django 5.2.17 on 2026-08-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_userprofile_monthly_switch_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_create_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền tạo sổ chuyển đổi TB tháng', verbose_name='Tạo sổ chuyển đổi TB tháng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_create_weekly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền tạo sổ chuyển đổi thiết bị tuần', verbose_name='Tạo sổ chuyển đổi thiết bị tuần'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền xóa sổ chuyển đổi TB tháng', verbose_name='Xóa sổ chuyển đổi TB tháng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_own_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền xóa sổ chuyển đổi TB tháng do mình tạo', verbose_name='Xóa sổ tháng do mình tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_own_weekly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền xóa sổ và lần chuyển đổi thiết bị tuần do mình tạo', verbose_name='Xóa sổ tuần do mình tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_weekly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền xóa sổ chuyển đổi thiết bị tuần', verbose_name='Xóa sổ chuyển đổi thiết bị tuần'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền sửa sổ chuyển đổi TB tháng', verbose_name='Sửa sổ chuyển đổi TB tháng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_own_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền sửa sổ chuyển đổi TB tháng do mình tạo', verbose_name='Sửa sổ tháng do mình tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_own_weekly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền sửa sổ và lần chuyển đổi thiết bị tuần do mình tạo', verbose_name='Sửa sổ tuần do mình tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_weekly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền sửa sổ chuyển đổi thiết bị tuần', verbose_name='Sửa sổ chuyển đổi thiết bị tuần'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_all_monthly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền sửa và xóa tất cả sổ chuyển đổi TB tháng', verbose_name='Quản lý tất cả sổ chuyển đổi TB tháng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_all_weekly_equipment_switch_logs',
            field=models.BooleanField(default=False, help_text='Có quyền sửa và xóa tất cả sổ chuyển đổi thiết bị tuần', verbose_name='Quản lý tất cả sổ chuyển đổi thiết bị tuần'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_monthly_equipment_switch_logs',
            field=models.BooleanField(default=True, help_text='Có quyền xem sổ chuyển đổi TB tháng', verbose_name='Xem sổ chuyển đổi TB tháng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_weekly_equipment_switch_logs',
            field=models.BooleanField(default=True, help_text='Có quyền xem sổ chuyển đổi thiết bị tuần', verbose_name='Xem sổ chuyển đổi thiết bị tuần'),
        ),
    ]
