# Generated by Django 5.2.17 on 2026-08-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_userprofile_can_create_monthly_equipment_switch_logs_and_more'),
        ('tochuc', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.AlterField(
            model_name='userprofile',
            name='nha_may',
            field=models.ForeignKey(blank=True, help_text='Nhà máy mà user được phép truy cập (null = tất cả nhà máy)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tochuc.nhamay'),
            )],
        ),
    ]
