# Generated by Django 5.2.17 on 2026-09-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_userprofile_organization_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_activate_shift_device_templates',
            field=models.BooleanField(default=False, help_text='Có quyền kích hoạt phiên bản mẫu trạng thái thiết bị'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shift_device_templates',
            field=models.BooleanField(default=False, help_text='Có quyền tạo mẫu và phiên bản mẫu trạng thái thiết bị'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_shift_device_templates',
            field=models.BooleanField(default=False, help_text='Có quyền xóa mẫu trạng thái thiết bị chưa được sử dụng'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_shift_device_templates',
            field=models.BooleanField(default=False, help_text='Có quyền đổi tiêu đề và cấu hình mẫu trạng thái thiết bị'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_shift_device_templates',
            field=models.BooleanField(default=True, help_text='Có quyền xem mẫu trạng thái thiết bị của sổ giao nhận ca vận hành'),
        ),
    ]
