# Generated by Django 5.2.17 on 2026-09-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_userprofile_can_activate_shift_device_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_activate_shift_summary_templates',
            field=models.BooleanField(default=False, help_text='Có quyền kích hoạt phiên bản mẫu tóm lược'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shift_summary_templates',
            field=models.BooleanField(default=False, help_text='Có quyền tạo mẫu và phiên bản mẫu tóm lược'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_shift_summary_templates',
            field=models.BooleanField(default=False, help_text='Có quyền xóa mẫu tóm lược chưa được sử dụng'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_shift_summary_templates',
            field=models.BooleanField(default=False, help_text='Có quyền sửa thông tin và cấu hình mẫu tóm lược'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_shift_summary_templates',
            field=models.BooleanField(default=True, help_text='Có quyền xem mẫu tóm lược của sổ giao nhận ca vận hành'),
        ),
    ]
