# Generated by Django 5.2.17 on 2026-09-07 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_userprofile_can_activate_shift_summary_templates_and_more'),
        ('tochuc', '0008_normalize_root_unit_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_assign_user_roles',
            field=models.BooleanField(default=False, verbose_name='Có quyền gán vai trò'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_users',
            field=models.BooleanField(default=False, verbose_name='Có quyền tạo tài khoản'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_users',
            field=models.BooleanField(default=False, verbose_name='Có quyền sửa tài khoản'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_user_status',
            field=models.BooleanField(default=False, verbose_name='Có quyền khóa/mở tài khoản'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_users',
            field=models.BooleanField(default=False, verbose_name='Có quyền xem tài khoản'),
        ),
        migrations.CreateModel(
            name='UserManagementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tochuc.nhamay')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử quản lý tài khoản',
                'verbose_name_plural': 'Lịch sử quản lý tài khoản',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignable_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userrole')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_delegations', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tochuc.nhamay')),
            ],
            options={
                'verbose_name': 'Ủy quyền cấp vai trò',
                'verbose_name_plural': 'Ủy quyền cấp vai trò',
                'constraints': [models.UniqueConstraint(fields=('delegate', 'nha_may', 'assignable_role'), name='unique_role_delegation')],
            },
        ),
    ]
