# Generated by Django 5.2.17 on 2026-09-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_user_session_version_and_more'),
        ('tochuc', '0008_normalize_root_unit_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='nha_may',
            field=models.ForeignKey(blank=True, help_text='Nhà máy snapshot tại thời điểm ghi nhận log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tochuc.nhamay', verbose_name='Nhà máy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_export_audit_logs',
            field=models.BooleanField(default=False, verbose_name='Có quyền xuất báo cáo kiểm toán'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_activity_logs',
            field=models.BooleanField(default=False, verbose_name='Có quyền xem nhật ký truy cập'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_data_audit_logs',
            field=models.BooleanField(default=False, verbose_name='Có quyền xem vết thay đổi dữ liệu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_user_management_audit',
            field=models.BooleanField(default=False, verbose_name='Có quyền xem lịch sử quản lý tài khoản'),
        ),
    ]
