# Generated by Django 5.2.17 on 2026-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_data_sync_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_export_night_shift_report',
            field=models.BooleanField(default=False, help_text='Có quyền xuất báo cáo ca đêm theo tháng', verbose_name='Có quyền xuất báo cáo ca đêm'),
        ),
    ]
