# Generated by Django 5.2.17 on 2026-09-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_userprofile_can_export_night_shift_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_activate_shift_command_templates',
            field=models.BooleanField(default=False, help_text='Có quyền kích hoạt phiên bản mẫu nội dung vận hành', verbose_name='Kích hoạt mẫu nội dung vận hành'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_shift_command_templates',
            field=models.BooleanField(default=False, help_text='Có quyền tạo mẫu và phiên bản mẫu nội dung vận hành', verbose_name='Tạo mẫu nội dung vận hành'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_shift_command_templates',
            field=models.BooleanField(default=False, help_text='Có quyền xóa mẫu nội dung vận hành', verbose_name='Xóa mẫu nội dung vận hành'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_shift_command_templates',
            field=models.BooleanField(default=False, help_text='Có quyền sửa tiêu đề, cú pháp và cấu hình mẫu nội dung vận hành', verbose_name='Sửa mẫu nội dung vận hành'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_shift_command_templates',
            field=models.BooleanField(default=False, help_text='Có quyền xem danh sách mẫu nội dung vận hành của sổ giao nhận ca vận hành', verbose_name='Xem mẫu nội dung vận hành'),
        ),
    ]
