# Generated by Django 5.2.17 on 2026-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_userprofile_shift_command_template_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_download_module_guides',
            field=models.BooleanField(default=False, verbose_name='Có quyền tải hướng dẫn module'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_module_guides',
            field=models.BooleanField(default=False, verbose_name='Có quyền quản lý hướng dẫn module'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_publish_module_guides',
            field=models.BooleanField(default=False, verbose_name='Có quyền phê duyệt hướng dẫn module'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_module_guide_history',
            field=models.BooleanField(default=False, verbose_name='Có quyền xem lịch sử hướng dẫn module'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_module_guides',
            field=models.BooleanField(default=False, verbose_name='Có quyền xem hướng dẫn module'),
        ),
    ]
