# Generated by Django 3.2.25 on 2026-06-12 08:39

from django.db import migrations
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
