# Generated by Django 3.2.25 on 2026-06-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='factory',
            field=models.CharField(choices=[('general', 'Chung'), ('songhinh', 'Song Hinh'), ('vinhson', 'Vinh Son'), ('thuongkontum', 'Thuong Kon Tum'), ('tckt', 'Phong TCKT'), ('khdt', 'Phong KHDT'), ('th', 'Phong TH'), ('kt', 'Phong KT')], default='general', max_length=40),
        ),
    ]
