# Generated by Django 5.2.17 on 2026-09-16 07:58

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20260618_1645'),
        ('tochuc', '0008_normalize_root_unit_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(choices=[('so_giao_nhan_ca_vh', 'Sổ giao nhận ca vận hành'), ('so_giao_nhan_ca_hc', 'Sổ giao nhận ca hành chính'), ('so_chuyen_doi_tuan', 'Sổ chuyển đổi thiết bị tuần'), ('so_chuyen_doi_thang', 'Sổ chuyển đổi thiết bị đầu tháng'), ('so_an_toan_dau_gio', 'Sổ theo dõi an toàn đầu giờ'), ('so_bchc_song_hinh', 'Sổ báo cáo hồ chứa Sông Hinh'), ('so_nhat_ky_diesel', 'Sổ nhật ký vận hành Diesel'), ('so_nhat_ky_van_hanh', 'Sổ nhật ký vận hành chung'), ('nhat_ky_su_kien', 'Nhật ký sự kiện'), ('quan_ly_thiet_bi', 'Quản lý thiết bị'), ('thong_so_van_hanh', 'Thông số vận hành')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255, verbose_name='Tên quy trình / hướng dẫn')),
                ('document_kind', models.CharField(choices=[('procedure', 'Quy trình tiêu chuẩn (SOP)'), ('instruction', 'Hướng dẫn thao tác'), ('form', 'Biểu mẫu / Bảng kiểm'), ('drawing', 'Bản vẽ / Sơ đồ nguyên lý')], default='procedure', max_length=20)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('version_label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Dự thảo / Nháp'), ('published', 'Đang áp dụng'), ('retired', 'Đã thu hồi / Lưu trữ')], db_index=True, default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('quick_guide', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='module_guides/%Y/%m/', validators=[documents.models.validate_module_guide_file])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retire_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_module_guides', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_module_guides', to=settings.AUTH_USER_MODEL)),
                ('nha_may', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_guides', to='tochuc.nhamay')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_module_guides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vanhanh_module_guide',
                'ordering': ('-is_primary', 'order', '-published_at', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True), ('nha_may__isnull', False), ('status', 'published')), fields=('module_code', 'nha_may'), name='unique_published_plant_primary_guide'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('nha_may__isnull', True), ('status', 'published')), fields=('module_code',), name='unique_published_global_primary_guide'), models.UniqueConstraint(condition=models.Q(('is_primary', False), ('nha_may__isnull', False), ('status', 'published')), fields=('module_code', 'nha_may', 'document_kind', 'order'), name='unique_published_plant_supp_guide'), models.UniqueConstraint(condition=models.Q(('is_primary', False), ('nha_may__isnull', True), ('status', 'published')), fields=('module_code', 'document_kind', 'order'), name='unique_published_global_supp_guide'), models.UniqueConstraint(condition=models.Q(('nha_may__isnull', False)), fields=('module_code', 'nha_may', 'is_primary', 'document_kind', 'order', 'version_label'), name='unique_plant_module_guide_version'), models.UniqueConstraint(condition=models.Q(('nha_may__isnull', True)), fields=('module_code', 'is_primary', 'document_kind', 'order', 'version_label'), name='unique_global_module_guide_version')],
            },
        ),
    ]
