name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare environment file
        run: cp .env.example .env
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Check migrations
        run: docker compose run --rm app sh -c "python manage.py makemigrations --check --dry-run"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
